import type { PricingBucket, SpeechModel, VoiceData } from "./types";

/** Accounting specifics paired with a SpeechModel. */
type VoiceCategory = {
    /** The pricing bucket that the voice will be billed against. */
    bucket: PricingBucket;
    /** `true` to count the billing units per byte; `false` to count them per character. */
    countBytes: boolean;
    /** The type of the synthesis model used by the voice. */
    speechModel: SpeechModel;
};

// Generated from https://cloud.google.com/text-to-speech/pricing?hl=en
const categories: ReadonlyArray<VoiceCategory> = [
    // TODO: the Casual voice is still a preview; no clue which bucket it's in
    { speechModel: "Casual", bucket: "Studio", countBytes: true },
    { speechModel: "Chirp", bucket: "Chirp", countBytes: true },
    { speechModel: "Neural", bucket: "Neural", countBytes: true },
    { speechModel: "News", bucket: "Studio", countBytes: true },
    { speechModel: "Polyglot", bucket: "Polyglot", countBytes: true },
    { speechModel: "Standard", bucket: "Standard", countBytes: false },
    { speechModel: "Studio", bucket: "Studio", countBytes: true },
    { speechModel: "Wavenet", bucket: "Wavenet", countBytes: false },
];

// Generated from https://cloud.google.com/text-to-speech/docs/voices
const allVoices: ReadonlyArray<VoiceData> = [
    { language: "Afrikaans (South Africa)", name: "af-ZA-Standard-A", gender: "Female" },
    { language: "Arabic", name: "ar-XA-Chirp3-HD-Aoede", gender: "Female" },
    { language: "Arabic", name: "ar-XA-Chirp3-HD-Charon", gender: "Male" },
    { language: "Arabic", name: "ar-XA-Chirp3-HD-Fenrir", gender: "Male" },
    { language: "Arabic", name: "ar-XA-Chirp3-HD-Kore", gender: "Female" },
    { language: "Arabic", name: "ar-XA-Chirp3-HD-Leda", gender: "Female" },
    { language: "Arabic", name: "ar-XA-Chirp3-HD-Orus", gender: "Male" },
    { language: "Arabic", name: "ar-XA-Chirp3-HD-Puck", gender: "Male" },
    { language: "Arabic", name: "ar-XA-Chirp3-HD-Zephyr", gender: "Female" },
    { language: "Arabic", name: "ar-XA-Standard-A", gender: "Female" },
    { language: "Arabic", name: "ar-XA-Standard-B", gender: "Male" },
    { language: "Arabic", name: "ar-XA-Standard-C", gender: "Male" },
    { language: "Arabic", name: "ar-XA-Standard-D", gender: "Female" },
    { language: "Arabic", name: "ar-XA-Wavenet-A", gender: "Female" },
    { language: "Arabic", name: "ar-XA-Wavenet-B", gender: "Male" },
    { language: "Arabic", name: "ar-XA-Wavenet-C", gender: "Male" },
    { language: "Arabic", name: "ar-XA-Wavenet-D", gender: "Female" },
    { language: "Bulgarian (Bulgaria)", name: "bg-BG-Standard-A", gender: "Female" },
    { language: "Bulgarian (Bulgaria)", name: "bg-BG-Standard-B", gender: "Female" },
    { language: "Bengali (India)", name: "bn-IN-Chirp3-HD-Aoede", gender: "Female" },
    { language: "Bengali (India)", name: "bn-IN-Chirp3-HD-Charon", gender: "Male" },
    { language: "Bengali (India)", name: "bn-IN-Chirp3-HD-Fenrir", gender: "Male" },
    { language: "Bengali (India)", name: "bn-IN-Chirp3-HD-Kore", gender: "Female" },
    { language: "Bengali (India)", name: "bn-IN-Chirp3-HD-Leda", gender: "Female" },
    { language: "Bengali (India)", name: "bn-IN-Chirp3-HD-Orus", gender: "Male" },
    { language: "Bengali (India)", name: "bn-IN-Chirp3-HD-Puck", gender: "Male" },
    { language: "Bengali (India)", name: "bn-IN-Chirp3-HD-Zephyr", gender: "Female" },
    { language: "Bengali (India)", name: "bn-IN-Standard-A", gender: "Female" },
    { language: "Bengali (India)", name: "bn-IN-Standard-B", gender: "Male" },
    { language: "Bengali (India)", name: "bn-IN-Standard-C", gender: "Female" },
    { language: "Bengali (India)", name: "bn-IN-Standard-D", gender: "Male" },
    { language: "Bengali (India)", name: "bn-IN-Wavenet-A", gender: "Female" },
    { language: "Bengali (India)", name: "bn-IN-Wavenet-B", gender: "Male" },
    { language: "Bengali (India)", name: "bn-IN-Wavenet-C", gender: "Female" },
    { language: "Bengali (India)", name: "bn-IN-Wavenet-D", gender: "Male" },
    { language: "Catalan (Spain)", name: "ca-ES-Standard-A", gender: "Female" },
    { language: "Catalan (Spain)", name: "ca-ES-Standard-B", gender: "Female" },
    { language: "Mandarin Chinese", name: "cmn-CN-Chirp3-HD-Aoede", gender: "Female" },
    { language: "Mandarin Chinese", name: "cmn-CN-Chirp3-HD-Charon", gender: "Male" },
    { language: "Mandarin Chinese", name: "cmn-CN-Chirp3-HD-Fenrir", gender: "Male" },
    { language: "Mandarin Chinese", name: "cmn-CN-Chirp3-HD-Kore", gender: "Female" },
    { language: "Mandarin Chinese", name: "cmn-CN-Chirp3-HD-Leda", gender: "Female" },
    { language: "Mandarin Chinese", name: "cmn-CN-Chirp3-HD-Orus", gender: "Male" },
    { language: "Mandarin Chinese", name: "cmn-CN-Chirp3-HD-Puck", gender: "Male" },
    { language: "Mandarin Chinese", name: "cmn-CN-Chirp3-HD-Zephyr", gender: "Female" },
    { language: "Mandarin Chinese", name: "cmn-CN-Standard-A", gender: "Female" },
    { language: "Mandarin Chinese", name: "cmn-CN-Standard-B", gender: "Male" },
    { language: "Mandarin Chinese", name: "cmn-CN-Standard-C", gender: "Male" },
    { language: "Mandarin Chinese", name: "cmn-CN-Standard-D", gender: "Female" },
    { language: "Mandarin Chinese", name: "cmn-CN-Wavenet-A", gender: "Female" },
    { language: "Mandarin Chinese", name: "cmn-CN-Wavenet-B", gender: "Male" },
    { language: "Mandarin Chinese", name: "cmn-CN-Wavenet-C", gender: "Male" },
    { language: "Mandarin Chinese", name: "cmn-CN-Wavenet-D", gender: "Female" },
    { language: "Mandarin Chinese", name: "cmn-TW-Standard-A", gender: "Female" },
    { language: "Mandarin Chinese", name: "cmn-TW-Standard-B", gender: "Male" },
    { language: "Mandarin Chinese", name: "cmn-TW-Standard-C", gender: "Male" },
    { language: "Mandarin Chinese", name: "cmn-TW-Wavenet-A", gender: "Female" },
    { language: "Mandarin Chinese", name: "cmn-TW-Wavenet-B", gender: "Male" },
    { language: "Mandarin Chinese", name: "cmn-TW-Wavenet-C", gender: "Male" },
    { language: "Czech (Czech Republic)", name: "cs-CZ-Standard-A", gender: "Female" },
    { language: "Czech (Czech Republic)", name: "cs-CZ-Standard-B", gender: "Female" },
    { language: "Czech (Czech Republic)", name: "cs-CZ-Wavenet-A", gender: "Female" },
    { language: "Czech (Czech Republic)", name: "cs-CZ-Wavenet-B", gender: "Female" },
    { language: "Danish (Denmark)", name: "da-DK-Neural2-F", gender: "Female" },
    { language: "Danish (Denmark)", name: "da-DK-Standard-A", gender: "Female" },
    { language: "Danish (Denmark)", name: "da-DK-Standard-C", gender: "Male" },
    { language: "Danish (Denmark)", name: "da-DK-Standard-D", gender: "Female" },
    { language: "Danish (Denmark)", name: "da-DK-Standard-E", gender: "Female" },
    { language: "Danish (Denmark)", name: "da-DK-Standard-F", gender: "Female" },
    { language: "Danish (Denmark)", name: "da-DK-Standard-G", gender: "Male" },
    { language: "Danish (Denmark)", name: "da-DK-Wavenet-A", gender: "Female" },
    { language: "Danish (Denmark)", name: "da-DK-Wavenet-C", gender: "Male" },
    { language: "Danish (Denmark)", name: "da-DK-Wavenet-D", gender: "Female" },
    { language: "Danish (Denmark)", name: "da-DK-Wavenet-E", gender: "Female" },
    { language: "Danish (Denmark)", name: "da-DK-Wavenet-F", gender: "Female" },
    { language: "Danish (Denmark)", name: "da-DK-Wavenet-G", gender: "Male" },
    { language: "German (Germany)", name: "de-DE-Chirp-HD-D", gender: "Male" },
    { language: "German (Germany)", name: "de-DE-Chirp-HD-F", gender: "Female" },
    { language: "German (Germany)", name: "de-DE-Chirp-HD-O", gender: "Female" },
    { language: "German (Germany)", name: "de-DE-Chirp3-HD-Aoede", gender: "Female" },
    { language: "German (Germany)", name: "de-DE-Chirp3-HD-Charon", gender: "Male" },
    { language: "German (Germany)", name: "de-DE-Chirp3-HD-Fenrir", gender: "Male" },
    { language: "German (Germany)", name: "de-DE-Chirp3-HD-Kore", gender: "Female" },
    { language: "German (Germany)", name: "de-DE-Chirp3-HD-Leda", gender: "Female" },
    { language: "German (Germany)", name: "de-DE-Chirp3-HD-Orus", gender: "Male" },
    { language: "German (Germany)", name: "de-DE-Chirp3-HD-Puck", gender: "Male" },
    { language: "German (Germany)", name: "de-DE-Chirp3-HD-Zephyr", gender: "Female" },
    { language: "German (Germany)", name: "de-DE-Neural2-G", gender: "Female" },
    { language: "German (Germany)", name: "de-DE-Neural2-H", gender: "Male" },
    { language: "German (Germany)", name: "de-DE-Polyglot-1", gender: "Male" },
    { language: "German (Germany)", name: "de-DE-Standard-A", gender: "Female" },
    { language: "German (Germany)", name: "de-DE-Standard-B", gender: "Male" },
    { language: "German (Germany)", name: "de-DE-Standard-C", gender: "Female" },
    { language: "German (Germany)", name: "de-DE-Standard-D", gender: "Male" },
    { language: "German (Germany)", name: "de-DE-Standard-E", gender: "Male" },
    { language: "German (Germany)", name: "de-DE-Standard-F", gender: "Female" },
    { language: "German (Germany)", name: "de-DE-Standard-G", gender: "Female" },
    { language: "German (Germany)", name: "de-DE-Standard-H", gender: "Male" },
    { language: "German (Germany)", name: "de-DE-Studio-B", gender: "Male" },
    { language: "German (Germany)", name: "de-DE-Studio-C", gender: "Female" },
    { language: "German (Germany)", name: "de-DE-Wavenet-A", gender: "Female" },
    { language: "German (Germany)", name: "de-DE-Wavenet-B", gender: "Male" },
    { language: "German (Germany)", name: "de-DE-Wavenet-C", gender: "Female" },
    { language: "German (Germany)", name: "de-DE-Wavenet-D", gender: "Male" },
    { language: "German (Germany)", name: "de-DE-Wavenet-E", gender: "Male" },
    { language: "German (Germany)", name: "de-DE-Wavenet-F", gender: "Female" },
    { language: "German (Germany)", name: "de-DE-Wavenet-G", gender: "Female" },
    { language: "German (Germany)", name: "de-DE-Wavenet-H", gender: "Male" },
    { language: "Greek (Greece)", name: "el-GR-Standard-A", gender: "Female" },
    { language: "Greek (Greece)", name: "el-GR-Standard-B", gender: "Female" },
    { language: "Greek (Greece)", name: "el-GR-Wavenet-A", gender: "Female" },
    { language: "Greek (Greece)", name: "el-GR-Wavenet-B", gender: "Female" },
    { language: "English (Australia)", name: "en-AU-Chirp-HD-D", gender: "Male" },
    { language: "English (Australia)", name: "en-AU-Chirp-HD-F", gender: "Female" },
    { language: "English (Australia)", name: "en-AU-Chirp-HD-O", gender: "Female" },
    { language: "English (Australia)", name: "en-AU-Chirp3-HD-Aoede", gender: "Female" },
    { language: "English (Australia)", name: "en-AU-Chirp3-HD-Charon", gender: "Male" },
    { language: "English (Australia)", name: "en-AU-Chirp3-HD-Fenrir", gender: "Male" },
    { language: "English (Australia)", name: "en-AU-Chirp3-HD-Kore", gender: "Female" },
    { language: "English (Australia)", name: "en-AU-Chirp3-HD-Leda", gender: "Female" },
    { language: "English (Australia)", name: "en-AU-Chirp3-HD-Orus", gender: "Male" },
    { language: "English (Australia)", name: "en-AU-Chirp3-HD-Puck", gender: "Male" },
    { language: "English (Australia)", name: "en-AU-Chirp3-HD-Zephyr", gender: "Female" },
    { language: "English (Australia)", name: "en-AU-Neural2-A", gender: "Female" },
    { language: "English (Australia)", name: "en-AU-Neural2-B", gender: "Male" },
    { language: "English (Australia)", name: "en-AU-Neural2-C", gender: "Female" },
    { language: "English (Australia)", name: "en-AU-Neural2-D", gender: "Male" },
    { language: "English (Australia)", name: "en-AU-News-E", gender: "Female" },
    { language: "English (Australia)", name: "en-AU-News-F", gender: "Female" },
    { language: "English (Australia)", name: "en-AU-News-G", gender: "Male" },
    { language: "English (Australia)", name: "en-AU-Polyglot-1", gender: "Male" },
    { language: "English (Australia)", name: "en-AU-Standard-A", gender: "Female" },
    { language: "English (Australia)", name: "en-AU-Standard-B", gender: "Male" },
    { language: "English (Australia)", name: "en-AU-Standard-C", gender: "Female" },
    { language: "English (Australia)", name: "en-AU-Standard-D", gender: "Male" },
    { language: "English (Australia)", name: "en-AU-Wavenet-A", gender: "Female" },
    { language: "English (Australia)", name: "en-AU-Wavenet-B", gender: "Male" },
    { language: "English (Australia)", name: "en-AU-Wavenet-C", gender: "Female" },
    { language: "English (Australia)", name: "en-AU-Wavenet-D", gender: "Male" },
    { language: "English (UK)", name: "en-GB-Chirp-HD-D", gender: "Male" },
    { language: "English (UK)", name: "en-GB-Chirp-HD-F", gender: "Female" },
    { language: "English (UK)", name: "en-GB-Chirp-HD-O", gender: "Female" },
    { language: "English (UK)", name: "en-GB-Chirp3-HD-Aoede", gender: "Female" },
    { language: "English (UK)", name: "en-GB-Chirp3-HD-Charon", gender: "Male" },
    { language: "English (UK)", name: "en-GB-Chirp3-HD-Fenrir", gender: "Male" },
    { language: "English (UK)", name: "en-GB-Chirp3-HD-Kore", gender: "Female" },
    { language: "English (UK)", name: "en-GB-Chirp3-HD-Leda", gender: "Female" },
    { language: "English (UK)", name: "en-GB-Chirp3-HD-Orus", gender: "Male" },
    { language: "English (UK)", name: "en-GB-Chirp3-HD-Puck", gender: "Male" },
    { language: "English (UK)", name: "en-GB-Chirp3-HD-Zephyr", gender: "Female" },
    { language: "English (UK)", name: "en-GB-Neural2-A", gender: "Female" },
    { language: "English (UK)", name: "en-GB-Neural2-B", gender: "Male" },
    { language: "English (UK)", name: "en-GB-Neural2-C", gender: "Female" },
    { language: "English (UK)", name: "en-GB-Neural2-D", gender: "Male" },
    { language: "English (UK)", name: "en-GB-Neural2-F", gender: "Female" },
    { language: "English (UK)", name: "en-GB-Neural2-N", gender: "Female" },
    { language: "English (UK)", name: "en-GB-Neural2-O", gender: "Male" },
    { language: "English (UK)", name: "en-GB-News-G", gender: "Female" },
    { language: "English (UK)", name: "en-GB-News-H", gender: "Female" },
    { language: "English (UK)", name: "en-GB-News-I", gender: "Female" },
    { language: "English (UK)", name: "en-GB-News-J", gender: "Male" },
    { language: "English (UK)", name: "en-GB-News-K", gender: "Male" },
    { language: "English (UK)", name: "en-GB-News-L", gender: "Male" },
    { language: "English (UK)", name: "en-GB-News-M", gender: "Male" },
    { language: "English (UK)", name: "en-GB-Standard-A", gender: "Female" },
    { language: "English (UK)", name: "en-GB-Standard-B", gender: "Male" },
    { language: "English (UK)", name: "en-GB-Standard-C", gender: "Female" },
    { language: "English (UK)", name: "en-GB-Standard-D", gender: "Male" },
    { language: "English (UK)", name: "en-GB-Standard-F", gender: "Female" },
    { language: "English (UK)", name: "en-GB-Standard-N", gender: "Female" },
    { language: "English (UK)", name: "en-GB-Standard-O", gender: "Male" },
    { language: "English (UK)", name: "en-GB-Studio-B", gender: "Male" },
    { language: "English (UK)", name: "en-GB-Studio-C", gender: "Female" },
    { language: "English (UK)", name: "en-GB-Wavenet-A", gender: "Female" },
    { language: "English (UK)", name: "en-GB-Wavenet-B", gender: "Male" },
    { language: "English (UK)", name: "en-GB-Wavenet-C", gender: "Female" },
    { language: "English (UK)", name: "en-GB-Wavenet-D", gender: "Male" },
    { language: "English (UK)", name: "en-GB-Wavenet-F", gender: "Female" },
    { language: "English (UK)", name: "en-GB-Wavenet-N", gender: "Female" },
    { language: "English (UK)", name: "en-GB-Wavenet-O", gender: "Male" },
    { language: "English (India)", name: "en-IN-Chirp-HD-D", gender: "Male" },
    { language: "English (India)", name: "en-IN-Chirp-HD-F", gender: "Female" },
    { language: "English (India)", name: "en-IN-Chirp-HD-O", gender: "Female" },
    { language: "English (India)", name: "en-IN-Chirp3-HD-Aoede", gender: "Female" },
    { language: "English (India)", name: "en-IN-Chirp3-HD-Charon", gender: "Male" },
    { language: "English (India)", name: "en-IN-Chirp3-HD-Fenrir", gender: "Male" },
    { language: "English (India)", name: "en-IN-Chirp3-HD-Kore", gender: "Female" },
    { language: "English (India)", name: "en-IN-Chirp3-HD-Leda", gender: "Female" },
    { language: "English (India)", name: "en-IN-Chirp3-HD-Orus", gender: "Male" },
    { language: "English (India)", name: "en-IN-Chirp3-HD-Puck", gender: "Male" },
    { language: "English (India)", name: "en-IN-Chirp3-HD-Zephyr", gender: "Female" },
    { language: "English (India)", name: "en-IN-Neural2-A", gender: "Female" },
    { language: "English (India)", name: "en-IN-Neural2-B", gender: "Male" },
    { language: "English (India)", name: "en-IN-Neural2-C", gender: "Male" },
    { language: "English (India)", name: "en-IN-Neural2-D", gender: "Female" },
    { language: "English (India)", name: "en-IN-Standard-A", gender: "Female" },
    { language: "English (India)", name: "en-IN-Standard-B", gender: "Male" },
    { language: "English (India)", name: "en-IN-Standard-C", gender: "Male" },
    { language: "English (India)", name: "en-IN-Standard-D", gender: "Female" },
    { language: "English (India)", name: "en-IN-Standard-E", gender: "Female" },
    { language: "English (India)", name: "en-IN-Standard-F", gender: "Male" },
    { language: "English (India)", name: "en-IN-Wavenet-A", gender: "Female" },
    { language: "English (India)", name: "en-IN-Wavenet-B", gender: "Male" },
    { language: "English (India)", name: "en-IN-Wavenet-C", gender: "Male" },
    { language: "English (India)", name: "en-IN-Wavenet-D", gender: "Female" },
    { language: "English (India)", name: "en-IN-Wavenet-E", gender: "Female" },
    { language: "English (India)", name: "en-IN-Wavenet-F", gender: "Male" },
    { language: "English (US)", name: "en-US-Casual-K", gender: "Male" },
    { language: "English (US)", name: "en-US-Chirp-HD-D", gender: "Male" },
    { language: "English (US)", name: "en-US-Chirp-HD-F", gender: "Female" },
    { language: "English (US)", name: "en-US-Chirp-HD-O", gender: "Female" },
    { language: "English (US)", name: "en-US-Chirp3-HD-Aoede", gender: "Female" },
    { language: "English (US)", name: "en-US-Chirp3-HD-Charon", gender: "Male" },
    { language: "English (US)", name: "en-US-Chirp3-HD-Fenrir", gender: "Male" },
    { language: "English (US)", name: "en-US-Chirp3-HD-Kore", gender: "Female" },
    { language: "English (US)", name: "en-US-Chirp3-HD-Leda", gender: "Female" },
    { language: "English (US)", name: "en-US-Chirp3-HD-Orus", gender: "Male" },
    { language: "English (US)", name: "en-US-Chirp3-HD-Puck", gender: "Male" },
    { language: "English (US)", name: "en-US-Chirp3-HD-Zephyr", gender: "Female" },
    { language: "English (US)", name: "en-US-Neural2-A", gender: "Male" },
    { language: "English (US)", name: "en-US-Neural2-C", gender: "Female" },
    { language: "English (US)", name: "en-US-Neural2-D", gender: "Male" },
    { language: "English (US)", name: "en-US-Neural2-E", gender: "Female" },
    { language: "English (US)", name: "en-US-Neural2-F", gender: "Female" },
    { language: "English (US)", name: "en-US-Neural2-G", gender: "Female" },
    { language: "English (US)", name: "en-US-Neural2-H", gender: "Female" },
    { language: "English (US)", name: "en-US-Neural2-I", gender: "Male" },
    { language: "English (US)", name: "en-US-Neural2-J", gender: "Male" },
    { language: "English (US)", name: "en-US-News-K", gender: "Female" },
    { language: "English (US)", name: "en-US-News-L", gender: "Female" },
    { language: "English (US)", name: "en-US-News-N", gender: "Male" },
    { language: "English (US)", name: "en-US-Polyglot-1", gender: "Male" },
    { language: "English (US)", name: "en-US-Standard-A", gender: "Male" },
    { language: "English (US)", name: "en-US-Standard-B", gender: "Male" },
    { language: "English (US)", name: "en-US-Standard-C", gender: "Female" },
    { language: "English (US)", name: "en-US-Standard-D", gender: "Male" },
    { language: "English (US)", name: "en-US-Standard-E", gender: "Female" },
    { language: "English (US)", name: "en-US-Standard-F", gender: "Female" },
    { language: "English (US)", name: "en-US-Standard-G", gender: "Female" },
    { language: "English (US)", name: "en-US-Standard-H", gender: "Female" },
    { language: "English (US)", name: "en-US-Standard-I", gender: "Male" },
    { language: "English (US)", name: "en-US-Standard-J", gender: "Male" },
    { language: "English (US)", name: "en-US-Studio-O", gender: "Female" },
    { language: "English (US)", name: "en-US-Studio-Q", gender: "Male" },
    { language: "English (US)", name: "en-US-Wavenet-A", gender: "Male" },
    { language: "English (US)", name: "en-US-Wavenet-B", gender: "Male" },
    { language: "English (US)", name: "en-US-Wavenet-C", gender: "Female" },
    { language: "English (US)", name: "en-US-Wavenet-D", gender: "Male" },
    { language: "English (US)", name: "en-US-Wavenet-E", gender: "Female" },
    { language: "English (US)", name: "en-US-Wavenet-F", gender: "Female" },
    { language: "English (US)", name: "en-US-Wavenet-G", gender: "Female" },
    { language: "English (US)", name: "en-US-Wavenet-H", gender: "Female" },
    { language: "English (US)", name: "en-US-Wavenet-I", gender: "Male" },
    { language: "English (US)", name: "en-US-Wavenet-J", gender: "Male" },
    { language: "Spanish (Spain)", name: "es-ES-Chirp-HD-D", gender: "Male" },
    { language: "Spanish (Spain)", name: "es-ES-Chirp-HD-F", gender: "Female" },
    { language: "Spanish (Spain)", name: "es-ES-Chirp-HD-O", gender: "Female" },
    { language: "Spanish (Spain)", name: "es-ES-Chirp3-HD-Aoede", gender: "Female" },
    { language: "Spanish (Spain)", name: "es-ES-Chirp3-HD-Charon", gender: "Male" },
    { language: "Spanish (Spain)", name: "es-ES-Chirp3-HD-Fenrir", gender: "Male" },
    { language: "Spanish (Spain)", name: "es-ES-Chirp3-HD-Kore", gender: "Female" },
    { language: "Spanish (Spain)", name: "es-ES-Chirp3-HD-Leda", gender: "Female" },
    { language: "Spanish (Spain)", name: "es-ES-Chirp3-HD-Orus", gender: "Male" },
    { language: "Spanish (Spain)", name: "es-ES-Chirp3-HD-Puck", gender: "Male" },
    { language: "Spanish (Spain)", name: "es-ES-Chirp3-HD-Zephyr", gender: "Female" },
    { language: "Spanish (Spain)", name: "es-ES-Neural2-A", gender: "Female" },
    { language: "Spanish (Spain)", name: "es-ES-Neural2-E", gender: "Female" },
    { language: "Spanish (Spain)", name: "es-ES-Neural2-F", gender: "Male" },
    { language: "Spanish (Spain)", name: "es-ES-Neural2-G", gender: "Male" },
    { language: "Spanish (Spain)", name: "es-ES-Neural2-H", gender: "Female" },
    { language: "Spanish (Spain)", name: "es-ES-Polyglot-1", gender: "Male" },
    { language: "Spanish (Spain)", name: "es-ES-Standard-A", gender: "Female" },
    { language: "Spanish (Spain)", name: "es-ES-Standard-B", gender: "Male" },
    { language: "Spanish (Spain)", name: "es-ES-Standard-C", gender: "Female" },
    { language: "Spanish (Spain)", name: "es-ES-Standard-D", gender: "Female" },
    { language: "Spanish (Spain)", name: "es-ES-Standard-E", gender: "Male" },
    { language: "Spanish (Spain)", name: "es-ES-Standard-F", gender: "Female" },
    { language: "Spanish (Spain)", name: "es-ES-Standard-G", gender: "Male" },
    { language: "Spanish (Spain)", name: "es-ES-Standard-H", gender: "Female" },
    { language: "Spanish (Spain)", name: "es-ES-Studio-C", gender: "Female" },
    { language: "Spanish (Spain)", name: "es-ES-Studio-F", gender: "Male" },
    { language: "Spanish (Spain)", name: "es-ES-Wavenet-B", gender: "Male" },
    { language: "Spanish (Spain)", name: "es-ES-Wavenet-C", gender: "Female" },
    { language: "Spanish (Spain)", name: "es-ES-Wavenet-D", gender: "Female" },
    { language: "Spanish (Spain)", name: "es-ES-Wavenet-E", gender: "Male" },
    { language: "Spanish (Spain)", name: "es-ES-Wavenet-F", gender: "Female" },
    { language: "Spanish (Spain)", name: "es-ES-Wavenet-G", gender: "Male" },
    { language: "Spanish (Spain)", name: "es-ES-Wavenet-H", gender: "Female" },
    { language: "Spanish (US)", name: "es-US-Chirp-HD-D", gender: "Male" },
    { language: "Spanish (US)", name: "es-US-Chirp-HD-F", gender: "Female" },
    { language: "Spanish (US)", name: "es-US-Chirp-HD-O", gender: "Female" },
    { language: "Spanish (US)", name: "es-US-Chirp3-HD-Aoede", gender: "Female" },
    { language: "Spanish (US)", name: "es-US-Chirp3-HD-Charon", gender: "Male" },
    { language: "Spanish (US)", name: "es-US-Chirp3-HD-Fenrir", gender: "Male" },
    { language: "Spanish (US)", name: "es-US-Chirp3-HD-Kore", gender: "Female" },
    { language: "Spanish (US)", name: "es-US-Chirp3-HD-Leda", gender: "Female" },
    { language: "Spanish (US)", name: "es-US-Chirp3-HD-Orus", gender: "Male" },
    { language: "Spanish (US)", name: "es-US-Chirp3-HD-Puck", gender: "Male" },
    { language: "Spanish (US)", name: "es-US-Chirp3-HD-Zephyr", gender: "Female" },
    { language: "Spanish (US)", name: "es-US-Neural2-A", gender: "Female" },
    { language: "Spanish (US)", name: "es-US-Neural2-B", gender: "Male" },
    { language: "Spanish (US)", name: "es-US-Neural2-C", gender: "Male" },
    { language: "Spanish (US)", name: "es-US-News-D", gender: "Male" },
    { language: "Spanish (US)", name: "es-US-News-E", gender: "Male" },
    { language: "Spanish (US)", name: "es-US-News-F", gender: "Female" },
    { language: "Spanish (US)", name: "es-US-News-G", gender: "Female" },
    { language: "Spanish (US)", name: "es-US-Polyglot-1", gender: "Male" },
    { language: "Spanish (US)", name: "es-US-Standard-A", gender: "Female" },
    { language: "Spanish (US)", name: "es-US-Standard-B", gender: "Male" },
    { language: "Spanish (US)", name: "es-US-Standard-C", gender: "Male" },
    { language: "Spanish (US)", name: "es-US-Studio-B", gender: "Male" },
    { language: "Spanish (US)", name: "es-US-Wavenet-A", gender: "Female" },
    { language: "Spanish (US)", name: "es-US-Wavenet-B", gender: "Male" },
    { language: "Spanish (US)", name: "es-US-Wavenet-C", gender: "Male" },
    { language: "Basque (Spain)", name: "eu-ES-Standard-A", gender: "Female" },
    { language: "Basque (Spain)", name: "eu-ES-Standard-B", gender: "Female" },
    { language: "Finnish (Finland)", name: "fi-FI-Standard-A", gender: "Female" },
    { language: "Finnish (Finland)", name: "fi-FI-Standard-B", gender: "Female" },
    { language: "Finnish (Finland)", name: "fi-FI-Wavenet-A", gender: "Female" },
    { language: "Finnish (Finland)", name: "fi-FI-Wavenet-B", gender: "Female" },
    { language: "Filipino (Philippines)", name: "fil-ph-Neural2-A", gender: "Female" },
    { language: "Filipino (Philippines)", name: "fil-ph-Neural2-D", gender: "Male" },
    { language: "Filipino (Philippines)", name: "fil-PH-Standard-A", gender: "Female" },
    { language: "Filipino (Philippines)", name: "fil-PH-Standard-B", gender: "Female" },
    { language: "Filipino (Philippines)", name: "fil-PH-Standard-C", gender: "Male" },
    { language: "Filipino (Philippines)", name: "fil-PH-Standard-D", gender: "Male" },
    { language: "Filipino (Philippines)", name: "fil-PH-Wavenet-A", gender: "Female" },
    { language: "Filipino (Philippines)", name: "fil-PH-Wavenet-B", gender: "Female" },
    { language: "Filipino (Philippines)", name: "fil-PH-Wavenet-C", gender: "Male" },
    { language: "Filipino (Philippines)", name: "fil-PH-Wavenet-D", gender: "Male" },
    { language: "French (Canada)", name: "fr-CA-Chirp-HD-D", gender: "Male" },
    { language: "French (Canada)", name: "fr-CA-Chirp-HD-F", gender: "Female" },
    { language: "French (Canada)", name: "fr-CA-Chirp-HD-O", gender: "Female" },
    { language: "French (Canada)", name: "fr-CA-Chirp3-HD-Aoede", gender: "Female" },
    { language: "French (Canada)", name: "fr-CA-Chirp3-HD-Charon", gender: "Male" },
    { language: "French (Canada)", name: "fr-CA-Chirp3-HD-Fenrir", gender: "Male" },
    { language: "French (Canada)", name: "fr-CA-Chirp3-HD-Kore", gender: "Female" },
    { language: "French (Canada)", name: "fr-CA-Chirp3-HD-Leda", gender: "Female" },
    { language: "French (Canada)", name: "fr-CA-Chirp3-HD-Orus", gender: "Male" },
    { language: "French (Canada)", name: "fr-CA-Chirp3-HD-Puck", gender: "Male" },
    { language: "French (Canada)", name: "fr-CA-Chirp3-HD-Zephyr", gender: "Female" },
    { language: "French (Canada)", name: "fr-CA-Neural2-A", gender: "Female" },
    { language: "French (Canada)", name: "fr-CA-Neural2-B", gender: "Male" },
    { language: "French (Canada)", name: "fr-CA-Neural2-C", gender: "Female" },
    { language: "French (Canada)", name: "fr-CA-Neural2-D", gender: "Male" },
    { language: "French (Canada)", name: "fr-CA-Standard-A", gender: "Female" },
    { language: "French (Canada)", name: "fr-CA-Standard-B", gender: "Male" },
    { language: "French (Canada)", name: "fr-CA-Standard-C", gender: "Female" },
    { language: "French (Canada)", name: "fr-CA-Standard-D", gender: "Male" },
    { language: "French (Canada)", name: "fr-CA-Wavenet-A", gender: "Female" },
    { language: "French (Canada)", name: "fr-CA-Wavenet-B", gender: "Male" },
    { language: "French (Canada)", name: "fr-CA-Wavenet-C", gender: "Female" },
    { language: "French (Canada)", name: "fr-CA-Wavenet-D", gender: "Male" },
    { language: "French (France)", name: "fr-FR-Chirp-HD-D", gender: "Male" },
    { language: "French (France)", name: "fr-FR-Chirp-HD-F", gender: "Female" },
    { language: "French (France)", name: "fr-FR-Chirp-HD-O", gender: "Female" },
    { language: "French (France)", name: "fr-FR-Chirp3-HD-Aoede", gender: "Female" },
    { language: "French (France)", name: "fr-FR-Chirp3-HD-Charon", gender: "Male" },
    { language: "French (France)", name: "fr-FR-Chirp3-HD-Fenrir", gender: "Male" },
    { language: "French (France)", name: "fr-FR-Chirp3-HD-Kore", gender: "Female" },
    { language: "French (France)", name: "fr-FR-Chirp3-HD-Leda", gender: "Female" },
    { language: "French (France)", name: "fr-FR-Chirp3-HD-Orus", gender: "Male" },
    { language: "French (France)", name: "fr-FR-Chirp3-HD-Puck", gender: "Male" },
    { language: "French (France)", name: "fr-FR-Chirp3-HD-Zephyr", gender: "Female" },
    { language: "French (France)", name: "fr-FR-Neural2-F", gender: "Female" },
    { language: "French (France)", name: "fr-FR-Neural2-G", gender: "Male" },
    { language: "French (France)", name: "fr-FR-Polyglot-1", gender: "Male" },
    { language: "French (France)", name: "fr-FR-Standard-A", gender: "Female" },
    { language: "French (France)", name: "fr-FR-Standard-B", gender: "Male" },
    { language: "French (France)", name: "fr-FR-Standard-C", gender: "Female" },
    { language: "French (France)", name: "fr-FR-Standard-D", gender: "Male" },
    { language: "French (France)", name: "fr-FR-Standard-E", gender: "Female" },
    { language: "French (France)", name: "fr-FR-Standard-F", gender: "Female" },
    { language: "French (France)", name: "fr-FR-Standard-G", gender: "Male" },
    { language: "French (France)", name: "fr-FR-Studio-A", gender: "Female" },
    { language: "French (France)", name: "fr-FR-Studio-D", gender: "Male" },
    { language: "French (France)", name: "fr-FR-Wavenet-A", gender: "Female" },
    { language: "French (France)", name: "fr-FR-Wavenet-B", gender: "Male" },
    { language: "French (France)", name: "fr-FR-Wavenet-C", gender: "Female" },
    { language: "French (France)", name: "fr-FR-Wavenet-D", gender: "Male" },
    { language: "French (France)", name: "fr-FR-Wavenet-E", gender: "Female" },
    { language: "French (France)", name: "fr-FR-Wavenet-F", gender: "Female" },
    { language: "French (France)", name: "fr-FR-Wavenet-G", gender: "Male" },
    { language: "Galician (Spain)", name: "gl-ES-Standard-A", gender: "Female" },
    { language: "Galician (Spain)", name: "gl-ES-Standard-B", gender: "Female" },
    { language: "Gujarati (India)", name: "gu-IN-Chirp3-HD-Aoede", gender: "Female" },
    { language: "Gujarati (India)", name: "gu-IN-Chirp3-HD-Charon", gender: "Male" },
    { language: "Gujarati (India)", name: "gu-IN-Chirp3-HD-Fenrir", gender: "Male" },
    { language: "Gujarati (India)", name: "gu-IN-Chirp3-HD-Kore", gender: "Female" },
    { language: "Gujarati (India)", name: "gu-IN-Chirp3-HD-Leda", gender: "Female" },
    { language: "Gujarati (India)", name: "gu-IN-Chirp3-HD-Orus", gender: "Male" },
    { language: "Gujarati (India)", name: "gu-IN-Chirp3-HD-Puck", gender: "Male" },
    { language: "Gujarati (India)", name: "gu-IN-Chirp3-HD-Zephyr", gender: "Female" },
    { language: "Gujarati (India)", name: "gu-IN-Standard-A", gender: "Female" },
    { language: "Gujarati (India)", name: "gu-IN-Standard-B", gender: "Male" },
    { language: "Gujarati (India)", name: "gu-IN-Standard-C", gender: "Female" },
    { language: "Gujarati (India)", name: "gu-IN-Standard-D", gender: "Male" },
    { language: "Gujarati (India)", name: "gu-IN-Wavenet-A", gender: "Female" },
    { language: "Gujarati (India)", name: "gu-IN-Wavenet-B", gender: "Male" },
    { language: "Gujarati (India)", name: "gu-IN-Wavenet-C", gender: "Female" },
    { language: "Gujarati (India)", name: "gu-IN-Wavenet-D", gender: "Male" },
    { language: "Hebrew (Israel)", name: "he-IL-Standard-A", gender: "Female" },
    { language: "Hebrew (Israel)", name: "he-IL-Standard-B", gender: "Male" },
    { language: "Hebrew (Israel)", name: "he-IL-Standard-C", gender: "Female" },
    { language: "Hebrew (Israel)", name: "he-IL-Standard-D", gender: "Male" },
    { language: "Hebrew (Israel)", name: "he-IL-Wavenet-A", gender: "Female" },
    { language: "Hebrew (Israel)", name: "he-IL-Wavenet-B", gender: "Male" },
    { language: "Hebrew (Israel)", name: "he-IL-Wavenet-C", gender: "Female" },
    { language: "Hebrew (Israel)", name: "he-IL-Wavenet-D", gender: "Male" },
    { language: "Hindi (India)", name: "hi-IN-Chirp3-HD-Aoede", gender: "Female" },
    { language: "Hindi (India)", name: "hi-IN-Chirp3-HD-Charon", gender: "Male" },
    { language: "Hindi (India)", name: "hi-IN-Chirp3-HD-Fenrir", gender: "Male" },
    { language: "Hindi (India)", name: "hi-IN-Chirp3-HD-Kore", gender: "Female" },
    { language: "Hindi (India)", name: "hi-IN-Chirp3-HD-Leda", gender: "Female" },
    { language: "Hindi (India)", name: "hi-IN-Chirp3-HD-Orus", gender: "Male" },
    { language: "Hindi (India)", name: "hi-IN-Chirp3-HD-Puck", gender: "Male" },
    { language: "Hindi (India)", name: "hi-IN-Chirp3-HD-Zephyr", gender: "Female" },
    { language: "Hindi (India)", name: "hi-IN-Neural2-A", gender: "Female" },
    { language: "Hindi (India)", name: "hi-IN-Neural2-B", gender: "Male" },
    { language: "Hindi (India)", name: "hi-IN-Neural2-C", gender: "Male" },
    { language: "Hindi (India)", name: "hi-IN-Neural2-D", gender: "Female" },
    { language: "Hindi (India)", name: "hi-IN-Standard-A", gender: "Female" },
    { language: "Hindi (India)", name: "hi-IN-Standard-B", gender: "Male" },
    { language: "Hindi (India)", name: "hi-IN-Standard-C", gender: "Male" },
    { language: "Hindi (India)", name: "hi-IN-Standard-D", gender: "Female" },
    { language: "Hindi (India)", name: "hi-IN-Standard-E", gender: "Female" },
    { language: "Hindi (India)", name: "hi-IN-Standard-F", gender: "Male" },
    { language: "Hindi (India)", name: "hi-IN-Wavenet-A", gender: "Female" },
    { language: "Hindi (India)", name: "hi-IN-Wavenet-B", gender: "Male" },
    { language: "Hindi (India)", name: "hi-IN-Wavenet-C", gender: "Male" },
    { language: "Hindi (India)", name: "hi-IN-Wavenet-D", gender: "Female" },
    { language: "Hindi (India)", name: "hi-IN-Wavenet-E", gender: "Female" },
    { language: "Hindi (India)", name: "hi-IN-Wavenet-F", gender: "Male" },
    { language: "Hungarian (Hungary)", name: "hu-HU-Standard-A", gender: "Female" },
    { language: "Hungarian (Hungary)", name: "hu-HU-Standard-B", gender: "Female" },
    { language: "Hungarian (Hungary)", name: "hu-HU-Wavenet-A", gender: "Female" },
    { language: "Indonesian (Indonesia)", name: "id-ID-Chirp3-HD-Aoede", gender: "Female" },
    { language: "Indonesian (Indonesia)", name: "id-ID-Chirp3-HD-Charon", gender: "Male" },
    { language: "Indonesian (Indonesia)", name: "id-ID-Chirp3-HD-Fenrir", gender: "Male" },
    { language: "Indonesian (Indonesia)", name: "id-ID-Chirp3-HD-Kore", gender: "Female" },
    { language: "Indonesian (Indonesia)", name: "id-ID-Chirp3-HD-Leda", gender: "Female" },
    { language: "Indonesian (Indonesia)", name: "id-ID-Chirp3-HD-Orus", gender: "Male" },
    { language: "Indonesian (Indonesia)", name: "id-ID-Chirp3-HD-Puck", gender: "Male" },
    { language: "Indonesian (Indonesia)", name: "id-ID-Chirp3-HD-Zephyr", gender: "Female" },
    { language: "Indonesian (Indonesia)", name: "id-ID-Standard-A", gender: "Female" },
    { language: "Indonesian (Indonesia)", name: "id-ID-Standard-B", gender: "Male" },
    { language: "Indonesian (Indonesia)", name: "id-ID-Standard-C", gender: "Male" },
    { language: "Indonesian (Indonesia)", name: "id-ID-Standard-D", gender: "Female" },
    { language: "Indonesian (Indonesia)", name: "id-ID-Wavenet-A", gender: "Female" },
    { language: "Indonesian (Indonesia)", name: "id-ID-Wavenet-B", gender: "Male" },
    { language: "Indonesian (Indonesia)", name: "id-ID-Wavenet-C", gender: "Male" },
    { language: "Indonesian (Indonesia)", name: "id-ID-Wavenet-D", gender: "Female" },
    { language: "Icelandic (Iceland)", name: "is-IS-Standard-A", gender: "Female" },
    { language: "Icelandic (Iceland)", name: "is-IS-Standard-B", gender: "Female" },
    { language: "Italian (Italy)", name: "it-IT-Chirp-HD-D", gender: "Male" },
    { language: "Italian (Italy)", name: "it-IT-Chirp-HD-F", gender: "Female" },
    { language: "Italian (Italy)", name: "it-IT-Chirp-HD-O", gender: "Female" },
    { language: "Italian (Italy)", name: "it-IT-Chirp3-HD-Aoede", gender: "Female" },
    { language: "Italian (Italy)", name: "it-IT-Chirp3-HD-Charon", gender: "Male" },
    { language: "Italian (Italy)", name: "it-IT-Chirp3-HD-Fenrir", gender: "Male" },
    { language: "Italian (Italy)", name: "it-IT-Chirp3-HD-Kore", gender: "Female" },
    { language: "Italian (Italy)", name: "it-IT-Chirp3-HD-Leda", gender: "Female" },
    { language: "Italian (Italy)", name: "it-IT-Chirp3-HD-Orus", gender: "Male" },
    { language: "Italian (Italy)", name: "it-IT-Chirp3-HD-Puck", gender: "Male" },
    { language: "Italian (Italy)", name: "it-IT-Chirp3-HD-Zephyr", gender: "Female" },
    { language: "Italian (Italy)", name: "it-IT-Neural2-A", gender: "Female" },
    { language: "Italian (Italy)", name: "it-IT-Neural2-E", gender: "Female" },
    { language: "Italian (Italy)", name: "it-IT-Neural2-F", gender: "Male" },
    { language: "Italian (Italy)", name: "it-IT-Standard-A", gender: "Female" },
    { language: "Italian (Italy)", name: "it-IT-Standard-B", gender: "Female" },
    { language: "Italian (Italy)", name: "it-IT-Standard-C", gender: "Male" },
    { language: "Italian (Italy)", name: "it-IT-Standard-D", gender: "Male" },
    { language: "Italian (Italy)", name: "it-IT-Standard-E", gender: "Female" },
    { language: "Italian (Italy)", name: "it-IT-Standard-F", gender: "Male" },
    { language: "Italian (Italy)", name: "it-IT-Wavenet-A", gender: "Female" },
    { language: "Italian (Italy)", name: "it-IT-Wavenet-B", gender: "Female" },
    { language: "Italian (Italy)", name: "it-IT-Wavenet-C", gender: "Male" },
    { language: "Italian (Italy)", name: "it-IT-Wavenet-D", gender: "Male" },
    { language: "Italian (Italy)", name: "it-IT-Wavenet-E", gender: "Female" },
    { language: "Italian (Italy)", name: "it-IT-Wavenet-F", gender: "Male" },
    { language: "Japanese (Japan)", name: "ja-JP-Chirp3-HD-Aoede", gender: "Female" },
    { language: "Japanese (Japan)", name: "ja-JP-Chirp3-HD-Charon", gender: "Male" },
    { language: "Japanese (Japan)", name: "ja-JP-Chirp3-HD-Fenrir", gender: "Male" },
    { language: "Japanese (Japan)", name: "ja-JP-Chirp3-HD-Kore", gender: "Female" },
    { language: "Japanese (Japan)", name: "ja-JP-Chirp3-HD-Leda", gender: "Female" },
    { language: "Japanese (Japan)", name: "ja-JP-Chirp3-HD-Orus", gender: "Male" },
    { language: "Japanese (Japan)", name: "ja-JP-Chirp3-HD-Puck", gender: "Male" },
    { language: "Japanese (Japan)", name: "ja-JP-Chirp3-HD-Zephyr", gender: "Female" },
    { language: "Japanese (Japan)", name: "ja-JP-Neural2-B", gender: "Female" },
    { language: "Japanese (Japan)", name: "ja-JP-Neural2-C", gender: "Male" },
    { language: "Japanese (Japan)", name: "ja-JP-Neural2-D", gender: "Male" },
    { language: "Japanese (Japan)", name: "ja-JP-Standard-A", gender: "Female" },
    { language: "Japanese (Japan)", name: "ja-JP-Standard-B", gender: "Female" },
    { language: "Japanese (Japan)", name: "ja-JP-Standard-C", gender: "Male" },
    { language: "Japanese (Japan)", name: "ja-JP-Standard-D", gender: "Male" },
    { language: "Japanese (Japan)", name: "ja-JP-Wavenet-A", gender: "Female" },
    { language: "Japanese (Japan)", name: "ja-JP-Wavenet-B", gender: "Female" },
    { language: "Japanese (Japan)", name: "ja-JP-Wavenet-C", gender: "Male" },
    { language: "Japanese (Japan)", name: "ja-JP-Wavenet-D", gender: "Male" },
    { language: "Kannada (India)", name: "kn-IN-Chirp3-HD-Aoede", gender: "Female" },
    { language: "Kannada (India)", name: "kn-IN-Chirp3-HD-Charon", gender: "Male" },
    { language: "Kannada (India)", name: "kn-IN-Chirp3-HD-Fenrir", gender: "Male" },
    { language: "Kannada (India)", name: "kn-IN-Chirp3-HD-Kore", gender: "Female" },
    { language: "Kannada (India)", name: "kn-IN-Chirp3-HD-Leda", gender: "Female" },
    { language: "Kannada (India)", name: "kn-IN-Chirp3-HD-Orus", gender: "Male" },
    { language: "Kannada (India)", name: "kn-IN-Chirp3-HD-Puck", gender: "Male" },
    { language: "Kannada (India)", name: "kn-IN-Chirp3-HD-Zephyr", gender: "Female" },
    { language: "Kannada (India)", name: "kn-IN-Standard-A", gender: "Female" },
    { language: "Kannada (India)", name: "kn-IN-Standard-B", gender: "Male" },
    { language: "Kannada (India)", name: "kn-IN-Standard-C", gender: "Female" },
    { language: "Kannada (India)", name: "kn-IN-Standard-D", gender: "Male" },
    { language: "Kannada (India)", name: "kn-IN-Wavenet-A", gender: "Female" },
    { language: "Kannada (India)", name: "kn-IN-Wavenet-B", gender: "Male" },
    { language: "Kannada (India)", name: "kn-IN-Wavenet-C", gender: "Female" },
    { language: "Kannada (India)", name: "kn-IN-Wavenet-D", gender: "Male" },
    { language: "Korean (South Korea)", name: "ko-KR-Chirp3-HD-Aoede", gender: "Female" },
    { language: "Korean (South Korea)", name: "ko-KR-Chirp3-HD-Charon", gender: "Male" },
    { language: "Korean (South Korea)", name: "ko-KR-Chirp3-HD-Fenrir", gender: "Male" },
    { language: "Korean (South Korea)", name: "ko-KR-Chirp3-HD-Kore", gender: "Female" },
    { language: "Korean (South Korea)", name: "ko-KR-Chirp3-HD-Leda", gender: "Female" },
    { language: "Korean (South Korea)", name: "ko-KR-Chirp3-HD-Orus", gender: "Male" },
    { language: "Korean (South Korea)", name: "ko-KR-Chirp3-HD-Puck", gender: "Male" },
    { language: "Korean (South Korea)", name: "ko-KR-Chirp3-HD-Zephyr", gender: "Female" },
    { language: "Korean (South Korea)", name: "ko-KR-Neural2-A", gender: "Female" },
    { language: "Korean (South Korea)", name: "ko-KR-Neural2-B", gender: "Female" },
    { language: "Korean (South Korea)", name: "ko-KR-Neural2-C", gender: "Male" },
    { language: "Korean (South Korea)", name: "ko-KR-Standard-A", gender: "Female" },
    { language: "Korean (South Korea)", name: "ko-KR-Standard-B", gender: "Female" },
    { language: "Korean (South Korea)", name: "ko-KR-Standard-C", gender: "Male" },
    { language: "Korean (South Korea)", name: "ko-KR-Standard-D", gender: "Male" },
    { language: "Korean (South Korea)", name: "ko-KR-Wavenet-A", gender: "Female" },
    { language: "Korean (South Korea)", name: "ko-KR-Wavenet-B", gender: "Female" },
    { language: "Korean (South Korea)", name: "ko-KR-Wavenet-C", gender: "Male" },
    { language: "Korean (South Korea)", name: "ko-KR-Wavenet-D", gender: "Male" },
    { language: "Lithuanian (Lithuania)", name: "lt-LT-Standard-A", gender: "Male" },
    { language: "Lithuanian (Lithuania)", name: "lt-LT-Standard-B", gender: "Male" },
    { language: "Latvian (Latvia)", name: "lv-LV-Standard-A", gender: "Male" },
    { language: "Latvian (Latvia)", name: "lv-LV-Standard-B", gender: "Male" },
    { language: "Malayalam (India)", name: "ml-IN-Chirp3-HD-Aoede", gender: "Female" },
    { language: "Malayalam (India)", name: "ml-IN-Chirp3-HD-Charon", gender: "Male" },
    { language: "Malayalam (India)", name: "ml-IN-Chirp3-HD-Fenrir", gender: "Male" },
    { language: "Malayalam (India)", name: "ml-IN-Chirp3-HD-Kore", gender: "Female" },
    { language: "Malayalam (India)", name: "ml-IN-Chirp3-HD-Leda", gender: "Female" },
    { language: "Malayalam (India)", name: "ml-IN-Chirp3-HD-Orus", gender: "Male" },
    { language: "Malayalam (India)", name: "ml-IN-Chirp3-HD-Puck", gender: "Male" },
    { language: "Malayalam (India)", name: "ml-IN-Chirp3-HD-Zephyr", gender: "Female" },
    { language: "Malayalam (India)", name: "ml-IN-Standard-A", gender: "Female" },
    { language: "Malayalam (India)", name: "ml-IN-Standard-B", gender: "Male" },
    { language: "Malayalam (India)", name: "ml-IN-Standard-C", gender: "Female" },
    { language: "Malayalam (India)", name: "ml-IN-Standard-D", gender: "Male" },
    { language: "Malayalam (India)", name: "ml-IN-Wavenet-A", gender: "Female" },
    { language: "Malayalam (India)", name: "ml-IN-Wavenet-B", gender: "Male" },
    { language: "Malayalam (India)", name: "ml-IN-Wavenet-C", gender: "Female" },
    { language: "Malayalam (India)", name: "ml-IN-Wavenet-D", gender: "Male" },
    { language: "Marathi (India)", name: "mr-IN-Chirp3-HD-Aoede", gender: "Female" },
    { language: "Marathi (India)", name: "mr-IN-Chirp3-HD-Charon", gender: "Male" },
    { language: "Marathi (India)", name: "mr-IN-Chirp3-HD-Fenrir", gender: "Male" },
    { language: "Marathi (India)", name: "mr-IN-Chirp3-HD-Kore", gender: "Female" },
    { language: "Marathi (India)", name: "mr-IN-Chirp3-HD-Leda", gender: "Female" },
    { language: "Marathi (India)", name: "mr-IN-Chirp3-HD-Orus", gender: "Male" },
    { language: "Marathi (India)", name: "mr-IN-Chirp3-HD-Puck", gender: "Male" },
    { language: "Marathi (India)", name: "mr-IN-Chirp3-HD-Zephyr", gender: "Female" },
    { language: "Marathi (India)", name: "mr-IN-Standard-A", gender: "Female" },
    { language: "Marathi (India)", name: "mr-IN-Standard-B", gender: "Male" },
    { language: "Marathi (India)", name: "mr-IN-Standard-C", gender: "Female" },
    { language: "Marathi (India)", name: "mr-IN-Wavenet-A", gender: "Female" },
    { language: "Marathi (India)", name: "mr-IN-Wavenet-B", gender: "Male" },
    { language: "Marathi (India)", name: "mr-IN-Wavenet-C", gender: "Female" },
    { language: "Malay (Malaysia)", name: "ms-MY-Standard-A", gender: "Female" },
    { language: "Malay (Malaysia)", name: "ms-MY-Standard-B", gender: "Male" },
    { language: "Malay (Malaysia)", name: "ms-MY-Standard-C", gender: "Female" },
    { language: "Malay (Malaysia)", name: "ms-MY-Standard-D", gender: "Male" },
    { language: "Malay (Malaysia)", name: "ms-MY-Wavenet-A", gender: "Female" },
    { language: "Malay (Malaysia)", name: "ms-MY-Wavenet-B", gender: "Male" },
    { language: "Malay (Malaysia)", name: "ms-MY-Wavenet-C", gender: "Female" },
    { language: "Malay (Malaysia)", name: "ms-MY-Wavenet-D", gender: "Male" },
    { language: "Norwegian (Norway)", name: "nb-NO-Standard-A", gender: "Female" },
    { language: "Norwegian (Norway)", name: "nb-NO-Standard-B", gender: "Male" },
    { language: "Norwegian (Norway)", name: "nb-NO-Standard-C", gender: "Female" },
    { language: "Norwegian (Norway)", name: "nb-NO-Standard-D", gender: "Male" },
    { language: "Norwegian (Norway)", name: "nb-NO-Standard-E", gender: "Female" },
    { language: "Norwegian (Norway)", name: "nb-NO-Standard-F", gender: "Female" },
    { language: "Norwegian (Norway)", name: "nb-NO-Standard-G", gender: "Male" },
    { language: "Norwegian (Norway)", name: "nb-NO-Wavenet-A", gender: "Female" },
    { language: "Norwegian (Norway)", name: "nb-NO-Wavenet-B", gender: "Male" },
    { language: "Norwegian (Norway)", name: "nb-NO-Wavenet-C", gender: "Female" },
    { language: "Norwegian (Norway)", name: "nb-NO-Wavenet-D", gender: "Male" },
    { language: "Norwegian (Norway)", name: "nb-NO-Wavenet-E", gender: "Female" },
    { language: "Norwegian (Norway)", name: "nb-NO-Wavenet-F", gender: "Female" },
    { language: "Norwegian (Norway)", name: "nb-NO-Wavenet-G", gender: "Male" },
    { language: "Dutch (Belgium)", name: "nl-BE-Standard-A", gender: "Female" },
    { language: "Dutch (Belgium)", name: "nl-BE-Standard-B", gender: "Male" },
    { language: "Dutch (Belgium)", name: "nl-BE-Standard-C", gender: "Female" },
    { language: "Dutch (Belgium)", name: "nl-BE-Standard-D", gender: "Male" },
    { language: "Dutch (Belgium)", name: "nl-BE-Wavenet-A", gender: "Female" },
    { language: "Dutch (Belgium)", name: "nl-BE-Wavenet-B", gender: "Male" },
    { language: "Dutch (Belgium)", name: "nl-BE-Wavenet-C", gender: "Female" },
    { language: "Dutch (Belgium)", name: "nl-BE-Wavenet-D", gender: "Male" },
    { language: "Dutch (Netherlands)", name: "nl-NL-Chirp3-HD-Aoede", gender: "Female" },
    { language: "Dutch (Netherlands)", name: "nl-NL-Chirp3-HD-Charon", gender: "Male" },
    { language: "Dutch (Netherlands)", name: "nl-NL-Chirp3-HD-Fenrir", gender: "Male" },
    { language: "Dutch (Netherlands)", name: "nl-NL-Chirp3-HD-Kore", gender: "Female" },
    { language: "Dutch (Netherlands)", name: "nl-NL-Chirp3-HD-Leda", gender: "Female" },
    { language: "Dutch (Netherlands)", name: "nl-NL-Chirp3-HD-Orus", gender: "Male" },
    { language: "Dutch (Netherlands)", name: "nl-NL-Chirp3-HD-Puck", gender: "Male" },
    { language: "Dutch (Netherlands)", name: "nl-NL-Chirp3-HD-Zephyr", gender: "Female" },
    { language: "Dutch (Netherlands)", name: "nl-NL-Standard-A", gender: "Female" },
    { language: "Dutch (Netherlands)", name: "nl-NL-Standard-B", gender: "Male" },
    { language: "Dutch (Netherlands)", name: "nl-NL-Standard-C", gender: "Male" },
    { language: "Dutch (Netherlands)", name: "nl-NL-Standard-D", gender: "Female" },
    { language: "Dutch (Netherlands)", name: "nl-NL-Standard-E", gender: "Female" },
    { language: "Dutch (Netherlands)", name: "nl-NL-Standard-F", gender: "Female" },
    { language: "Dutch (Netherlands)", name: "nl-NL-Standard-G", gender: "Male" },
    { language: "Dutch (Netherlands)", name: "nl-NL-Wavenet-A", gender: "Female" },
    { language: "Dutch (Netherlands)", name: "nl-NL-Wavenet-B", gender: "Male" },
    { language: "Dutch (Netherlands)", name: "nl-NL-Wavenet-C", gender: "Male" },
    { language: "Dutch (Netherlands)", name: "nl-NL-Wavenet-D", gender: "Female" },
    { language: "Dutch (Netherlands)", name: "nl-NL-Wavenet-E", gender: "Female" },
    { language: "Dutch (Netherlands)", name: "nl-NL-Wavenet-F", gender: "Female" },
    { language: "Dutch (Netherlands)", name: "nl-NL-Wavenet-G", gender: "Male" },
    { language: "Punjabi (India)", name: "pa-IN-Standard-A", gender: "Female" },
    { language: "Punjabi (India)", name: "pa-IN-Standard-B", gender: "Male" },
    { language: "Punjabi (India)", name: "pa-IN-Standard-C", gender: "Female" },
    { language: "Punjabi (India)", name: "pa-IN-Standard-D", gender: "Male" },
    { language: "Punjabi (India)", name: "pa-IN-Wavenet-A", gender: "Female" },
    { language: "Punjabi (India)", name: "pa-IN-Wavenet-B", gender: "Male" },
    { language: "Punjabi (India)", name: "pa-IN-Wavenet-C", gender: "Female" },
    { language: "Punjabi (India)", name: "pa-IN-Wavenet-D", gender: "Male" },
    { language: "Polish (Poland)", name: "pl-PL-Chirp3-HD-Aoede", gender: "Female" },
    { language: "Polish (Poland)", name: "pl-PL-Chirp3-HD-Charon", gender: "Male" },
    { language: "Polish (Poland)", name: "pl-PL-Chirp3-HD-Fenrir", gender: "Male" },
    { language: "Polish (Poland)", name: "pl-PL-Chirp3-HD-Kore", gender: "Female" },
    { language: "Polish (Poland)", name: "pl-PL-Chirp3-HD-Leda", gender: "Female" },
    { language: "Polish (Poland)", name: "pl-PL-Chirp3-HD-Orus", gender: "Male" },
    { language: "Polish (Poland)", name: "pl-PL-Chirp3-HD-Puck", gender: "Male" },
    { language: "Polish (Poland)", name: "pl-PL-Chirp3-HD-Zephyr", gender: "Female" },
    { language: "Polish (Poland)", name: "pl-PL-Standard-A", gender: "Female" },
    { language: "Polish (Poland)", name: "pl-PL-Standard-B", gender: "Male" },
    { language: "Polish (Poland)", name: "pl-PL-Standard-C", gender: "Male" },
    { language: "Polish (Poland)", name: "pl-PL-Standard-D", gender: "Female" },
    { language: "Polish (Poland)", name: "pl-PL-Standard-E", gender: "Female" },
    { language: "Polish (Poland)", name: "pl-PL-Standard-F", gender: "Female" },
    { language: "Polish (Poland)", name: "pl-PL-Standard-G", gender: "Male" },
    { language: "Polish (Poland)", name: "pl-PL-Wavenet-A", gender: "Female" },
    { language: "Polish (Poland)", name: "pl-PL-Wavenet-B", gender: "Male" },
    { language: "Polish (Poland)", name: "pl-PL-Wavenet-C", gender: "Male" },
    { language: "Polish (Poland)", name: "pl-PL-Wavenet-D", gender: "Female" },
    { language: "Polish (Poland)", name: "pl-PL-Wavenet-E", gender: "Female" },
    { language: "Polish (Poland)", name: "pl-PL-Wavenet-F", gender: "Female" },
    { language: "Polish (Poland)", name: "pl-PL-Wavenet-G", gender: "Male" },
    { language: "Portuguese (Brazil)", name: "pt-BR-Chirp3-HD-Aoede", gender: "Female" },
    { language: "Portuguese (Brazil)", name: "pt-BR-Chirp3-HD-Charon", gender: "Male" },
    { language: "Portuguese (Brazil)", name: "pt-BR-Chirp3-HD-Fenrir", gender: "Male" },
    { language: "Portuguese (Brazil)", name: "pt-BR-Chirp3-HD-Kore", gender: "Female" },
    { language: "Portuguese (Brazil)", name: "pt-BR-Chirp3-HD-Leda", gender: "Female" },
    { language: "Portuguese (Brazil)", name: "pt-BR-Chirp3-HD-Orus", gender: "Male" },
    { language: "Portuguese (Brazil)", name: "pt-BR-Chirp3-HD-Puck", gender: "Male" },
    { language: "Portuguese (Brazil)", name: "pt-BR-Chirp3-HD-Zephyr", gender: "Female" },
    { language: "Portuguese (Brazil)", name: "pt-BR-Neural2-A", gender: "Female" },
    { language: "Portuguese (Brazil)", name: "pt-BR-Neural2-B", gender: "Male" },
    { language: "Portuguese (Brazil)", name: "pt-BR-Neural2-C", gender: "Female" },
    { language: "Portuguese (Brazil)", name: "pt-BR-Standard-A", gender: "Female" },
    { language: "Portuguese (Brazil)", name: "pt-BR-Standard-B", gender: "Male" },
    { language: "Portuguese (Brazil)", name: "pt-BR-Standard-C", gender: "Female" },
    { language: "Portuguese (Brazil)", name: "pt-BR-Standard-D", gender: "Female" },
    { language: "Portuguese (Brazil)", name: "pt-BR-Standard-E", gender: "Male" },
    { language: "Portuguese (Brazil)", name: "pt-BR-Wavenet-A", gender: "Female" },
    { language: "Portuguese (Brazil)", name: "pt-BR-Wavenet-B", gender: "Male" },
    { language: "Portuguese (Brazil)", name: "pt-BR-Wavenet-C", gender: "Female" },
    { language: "Portuguese (Brazil)", name: "pt-BR-Wavenet-D", gender: "Female" },
    { language: "Portuguese (Brazil)", name: "pt-BR-Wavenet-E", gender: "Male" },
    { language: "Portuguese (Portugal)", name: "pt-PT-Standard-A", gender: "Female" },
    { language: "Portuguese (Portugal)", name: "pt-PT-Standard-B", gender: "Male" },
    { language: "Portuguese (Portugal)", name: "pt-PT-Standard-C", gender: "Male" },
    { language: "Portuguese (Portugal)", name: "pt-PT-Standard-D", gender: "Female" },
    { language: "Portuguese (Portugal)", name: "pt-PT-Standard-E", gender: "Female" },
    { language: "Portuguese (Portugal)", name: "pt-PT-Standard-F", gender: "Male" },
    { language: "Portuguese (Portugal)", name: "pt-PT-Wavenet-A", gender: "Female" },
    { language: "Portuguese (Portugal)", name: "pt-PT-Wavenet-B", gender: "Male" },
    { language: "Portuguese (Portugal)", name: "pt-PT-Wavenet-C", gender: "Male" },
    { language: "Portuguese (Portugal)", name: "pt-PT-Wavenet-D", gender: "Female" },
    { language: "Portuguese (Portugal)", name: "pt-PT-Wavenet-E", gender: "Female" },
    { language: "Portuguese (Portugal)", name: "pt-PT-Wavenet-F", gender: "Male" },
    { language: "Romanian (Romania)", name: "ro-RO-Standard-A", gender: "Female" },
    { language: "Romanian (Romania)", name: "ro-RO-Standard-B", gender: "Female" },
    { language: "Romanian (Romania)", name: "ro-RO-Wavenet-A", gender: "Female" },
    { language: "Romanian (Romania)", name: "ro-RO-Wavenet-B", gender: "Female" },
    { language: "Russian (Russia)", name: "ru-RU-Chirp3-HD-Aoede", gender: "Female" },
    { language: "Russian (Russia)", name: "ru-RU-Chirp3-HD-Charon", gender: "Male" },
    { language: "Russian (Russia)", name: "ru-RU-Chirp3-HD-Fenrir", gender: "Male" },
    { language: "Russian (Russia)", name: "ru-RU-Chirp3-HD-Kore", gender: "Female" },
    { language: "Russian (Russia)", name: "ru-RU-Chirp3-HD-Leda", gender: "Female" },
    { language: "Russian (Russia)", name: "ru-RU-Chirp3-HD-Orus", gender: "Male" },
    { language: "Russian (Russia)", name: "ru-RU-Chirp3-HD-Puck", gender: "Male" },
    { language: "Russian (Russia)", name: "ru-RU-Chirp3-HD-Zephyr", gender: "Female" },
    { language: "Russian (Russia)", name: "ru-RU-Standard-A", gender: "Female" },
    { language: "Russian (Russia)", name: "ru-RU-Standard-B", gender: "Male" },
    { language: "Russian (Russia)", name: "ru-RU-Standard-C", gender: "Female" },
    { language: "Russian (Russia)", name: "ru-RU-Standard-D", gender: "Male" },
    { language: "Russian (Russia)", name: "ru-RU-Standard-E", gender: "Female" },
    { language: "Russian (Russia)", name: "ru-RU-Wavenet-A", gender: "Female" },
    { language: "Russian (Russia)", name: "ru-RU-Wavenet-B", gender: "Male" },
    { language: "Russian (Russia)", name: "ru-RU-Wavenet-C", gender: "Female" },
    { language: "Russian (Russia)", name: "ru-RU-Wavenet-D", gender: "Male" },
    { language: "Russian (Russia)", name: "ru-RU-Wavenet-E", gender: "Female" },
    { language: "Slovak (Slovakia)", name: "sk-SK-Standard-A", gender: "Female" },
    { language: "Slovak (Slovakia)", name: "sk-SK-Standard-B", gender: "Female" },
    { language: "Slovak (Slovakia)", name: "sk-SK-Wavenet-A", gender: "Female" },
    { language: "Slovak (Slovakia)", name: "sk-SK-Wavenet-B", gender: "Female" },
    { language: "Serbian (Cyrillic)", name: "sr-RS-Standard-A", gender: "Female" },
    { language: "Swedish (Sweden)", name: "sv-SE-Standard-A", gender: "Female" },
    { language: "Swedish (Sweden)", name: "sv-SE-Standard-B", gender: "Female" },
    { language: "Swedish (Sweden)", name: "sv-SE-Standard-C", gender: "Female" },
    { language: "Swedish (Sweden)", name: "sv-SE-Standard-D", gender: "Male" },
    { language: "Swedish (Sweden)", name: "sv-SE-Standard-E", gender: "Male" },
    { language: "Swedish (Sweden)", name: "sv-SE-Standard-F", gender: "Female" },
    { language: "Swedish (Sweden)", name: "sv-SE-Standard-G", gender: "Male" },
    { language: "Swedish (Sweden)", name: "sv-SE-Wavenet-A", gender: "Female" },
    { language: "Swedish (Sweden)", name: "sv-SE-Wavenet-B", gender: "Female" },
    { language: "Swedish (Sweden)", name: "sv-SE-Wavenet-C", gender: "Male" },
    { language: "Swedish (Sweden)", name: "sv-SE-Wavenet-D", gender: "Female" },
    { language: "Swedish (Sweden)", name: "sv-SE-Wavenet-E", gender: "Male" },
    { language: "Swedish (Sweden)", name: "sv-SE-Wavenet-F", gender: "Female" },
    { language: "Swedish (Sweden)", name: "sv-SE-Wavenet-G", gender: "Male" },
    { language: "Tamil (India)", name: "ta-IN-Chirp3-HD-Aoede", gender: "Female" },
    { language: "Tamil (India)", name: "ta-IN-Chirp3-HD-Charon", gender: "Male" },
    { language: "Tamil (India)", name: "ta-IN-Chirp3-HD-Fenrir", gender: "Male" },
    { language: "Tamil (India)", name: "ta-IN-Chirp3-HD-Kore", gender: "Female" },
    { language: "Tamil (India)", name: "ta-IN-Chirp3-HD-Leda", gender: "Female" },
    { language: "Tamil (India)", name: "ta-IN-Chirp3-HD-Orus", gender: "Male" },
    { language: "Tamil (India)", name: "ta-IN-Chirp3-HD-Puck", gender: "Male" },
    { language: "Tamil (India)", name: "ta-IN-Chirp3-HD-Zephyr", gender: "Female" },
    { language: "Tamil (India)", name: "ta-IN-Standard-A", gender: "Female" },
    { language: "Tamil (India)", name: "ta-IN-Standard-B", gender: "Male" },
    { language: "Tamil (India)", name: "ta-IN-Standard-C", gender: "Female" },
    { language: "Tamil (India)", name: "ta-IN-Standard-D", gender: "Male" },
    { language: "Tamil (India)", name: "ta-IN-Wavenet-A", gender: "Female" },
    { language: "Tamil (India)", name: "ta-IN-Wavenet-B", gender: "Male" },
    { language: "Tamil (India)", name: "ta-IN-Wavenet-C", gender: "Female" },
    { language: "Tamil (India)", name: "ta-IN-Wavenet-D", gender: "Male" },
    { language: "Telugu (India)", name: "te-IN-Chirp3-HD-Aoede", gender: "Female" },
    { language: "Telugu (India)", name: "te-IN-Chirp3-HD-Charon", gender: "Male" },
    { language: "Telugu (India)", name: "te-IN-Chirp3-HD-Fenrir", gender: "Male" },
    { language: "Telugu (India)", name: "te-IN-Chirp3-HD-Kore", gender: "Female" },
    { language: "Telugu (India)", name: "te-IN-Chirp3-HD-Leda", gender: "Female" },
    { language: "Telugu (India)", name: "te-IN-Chirp3-HD-Orus", gender: "Male" },
    { language: "Telugu (India)", name: "te-IN-Chirp3-HD-Puck", gender: "Male" },
    { language: "Telugu (India)", name: "te-IN-Chirp3-HD-Zephyr", gender: "Female" },
    { language: "Telugu (India)", name: "te-IN-Standard-A", gender: "Female" },
    { language: "Telugu (India)", name: "te-IN-Standard-B", gender: "Male" },
    { language: "Telugu (India)", name: "te-IN-Standard-C", gender: "Female" },
    { language: "Telugu (India)", name: "te-IN-Standard-D", gender: "Male" },
    { language: "Thai (Thailand)", name: "th-TH-Chirp3-HD-Aoede", gender: "Female" },
    { language: "Thai (Thailand)", name: "th-TH-Chirp3-HD-Charon", gender: "Male" },
    { language: "Thai (Thailand)", name: "th-TH-Chirp3-HD-Fenrir", gender: "Male" },
    { language: "Thai (Thailand)", name: "th-TH-Chirp3-HD-Kore", gender: "Female" },
    { language: "Thai (Thailand)", name: "th-TH-Chirp3-HD-Leda", gender: "Female" },
    { language: "Thai (Thailand)", name: "th-TH-Chirp3-HD-Orus", gender: "Male" },
    { language: "Thai (Thailand)", name: "th-TH-Chirp3-HD-Puck", gender: "Male" },
    { language: "Thai (Thailand)", name: "th-TH-Chirp3-HD-Zephyr", gender: "Female" },
    { language: "Thai (Thailand)", name: "th-TH-Neural2-C", gender: "Female" },
    { language: "Thai (Thailand)", name: "th-TH-Standard-A", gender: "Female" },
    { language: "Turkish (Turkey)", name: "tr-TR-Chirp3-HD-Aoede", gender: "Female" },
    { language: "Turkish (Turkey)", name: "tr-TR-Chirp3-HD-Charon", gender: "Male" },
    { language: "Turkish (Turkey)", name: "tr-TR-Chirp3-HD-Fenrir", gender: "Male" },
    { language: "Turkish (Turkey)", name: "tr-TR-Chirp3-HD-Kore", gender: "Female" },
    { language: "Turkish (Turkey)", name: "tr-TR-Chirp3-HD-Leda", gender: "Female" },
    { language: "Turkish (Turkey)", name: "tr-TR-Chirp3-HD-Orus", gender: "Male" },
    { language: "Turkish (Turkey)", name: "tr-TR-Chirp3-HD-Puck", gender: "Male" },
    { language: "Turkish (Turkey)", name: "tr-TR-Chirp3-HD-Zephyr", gender: "Female" },
    { language: "Turkish (Turkey)", name: "tr-TR-Standard-A", gender: "Female" },
    { language: "Turkish (Turkey)", name: "tr-TR-Standard-B", gender: "Male" },
    { language: "Turkish (Turkey)", name: "tr-TR-Standard-C", gender: "Female" },
    { language: "Turkish (Turkey)", name: "tr-TR-Standard-D", gender: "Female" },
    { language: "Turkish (Turkey)", name: "tr-TR-Standard-E", gender: "Male" },
    { language: "Turkish (Turkey)", name: "tr-TR-Wavenet-A", gender: "Female" },
    { language: "Turkish (Turkey)", name: "tr-TR-Wavenet-B", gender: "Male" },
    { language: "Turkish (Turkey)", name: "tr-TR-Wavenet-C", gender: "Female" },
    { language: "Turkish (Turkey)", name: "tr-TR-Wavenet-D", gender: "Female" },
    { language: "Turkish (Turkey)", name: "tr-TR-Wavenet-E", gender: "Male" },
    { language: "Ukrainian (Ukraine)", name: "uk-UA-Standard-A", gender: "Female" },
    { language: "Ukrainian (Ukraine)", name: "uk-UA-Wavenet-A", gender: "Female" },
    { language: "Vietnamese (Vietnam)", name: "vi-VN-Chirp3-HD-Aoede", gender: "Female" },
    { language: "Vietnamese (Vietnam)", name: "vi-VN-Chirp3-HD-Charon", gender: "Male" },
    { language: "Vietnamese (Vietnam)", name: "vi-VN-Chirp3-HD-Fenrir", gender: "Male" },
    { language: "Vietnamese (Vietnam)", name: "vi-VN-Chirp3-HD-Kore", gender: "Female" },
    { language: "Vietnamese (Vietnam)", name: "vi-VN-Chirp3-HD-Leda", gender: "Female" },
    { language: "Vietnamese (Vietnam)", name: "vi-VN-Chirp3-HD-Orus", gender: "Male" },
    { language: "Vietnamese (Vietnam)", name: "vi-VN-Chirp3-HD-Puck", gender: "Male" },
    { language: "Vietnamese (Vietnam)", name: "vi-VN-Chirp3-HD-Zephyr", gender: "Female" },
    { language: "Vietnamese (Vietnam)", name: "vi-VN-Neural2-A", gender: "Female" },
    { language: "Vietnamese (Vietnam)", name: "vi-VN-Neural2-D", gender: "Male" },
    { language: "Vietnamese (Vietnam)", name: "vi-VN-Standard-A", gender: "Female" },
    { language: "Vietnamese (Vietnam)", name: "vi-VN-Standard-B", gender: "Male" },
    { language: "Vietnamese (Vietnam)", name: "vi-VN-Standard-C", gender: "Female" },
    { language: "Vietnamese (Vietnam)", name: "vi-VN-Standard-D", gender: "Male" },
    { language: "Vietnamese (Vietnam)", name: "vi-VN-Wavenet-A", gender: "Female" },
    { language: "Vietnamese (Vietnam)", name: "vi-VN-Wavenet-B", gender: "Male" },
    { language: "Vietnamese (Vietnam)", name: "vi-VN-Wavenet-C", gender: "Female" },
    { language: "Vietnamese (Vietnam)", name: "vi-VN-Wavenet-D", gender: "Male" },
    { language: "Chinese (Hong Kong)", name: "yue-HK-Standard-A", gender: "Female" },
    { language: "Chinese (Hong Kong)", name: "yue-HK-Standard-B", gender: "Male" },
    { language: "Chinese (Hong Kong)", name: "yue-HK-Standard-C", gender: "Female" },
    { language: "Chinese (Hong Kong)", name: "yue-HK-Standard-D", gender: "Male" },
];

export default {
    /** Get an array of tuples of a SpeechModel paired with some accounting specifics. */
    getAllCategories(): ReadonlyArray<VoiceCategory> { return categories; },
    /** Get an array of the names of all known pricing buckets. */
    getAllPricingBuckets(): ReadonlyArray<PricingBucket> { return categories.map(t => t.bucket).filter((v, n, a) => a.indexOf(v) === n); },
    /** Get an array of all known speech synthesis voice models. */
    getAllSpeechModels(): ReadonlyArray<SpeechModel> { return categories.map(t => t.speechModel); },
    /** Get an array of all of the voices supported by this plugin. */
    getSupportedVoices(): ReadonlyArray<VoiceData> { return allVoices; },

    getVoiceCategory(voiceName: string): VoiceCategory {
        return categories.find(cat => voiceName?.includes(cat.speechModel)) ??
            { speechModel: "Unknown", bucket: "Unknown", countBytes: true };
    },
    getVoiceGender(voiceName: string): "Female" | "Male" | null {
        const voice = allVoices.find(v => v.name === voiceName);
        if (voice != null) {
            return voice.gender;
        }
        return null;
    },
    getVoiceLangCode(voiceName: string, defaultValue: string = null): string | null {
        const parts = voiceName?.split("-", 2) ?? [];
        if (parts.length === 2 && parts[0] && parts[1]) {
          return `${parts[0]}-${parts[1]}`;
        }
        return defaultValue;
    },
    getVoicePricingBucket(voiceName: string): PricingBucket {
        return categories.find(cat => voiceName?.includes(cat.speechModel))?.bucket ?? "Unknown";
    },
    getVoiceSpeechModel(voiceName: string): SpeechModel {
        return categories.find(cat => voiceName?.includes(cat.speechModel))?.speechModel ?? "Unknown";
    },
    /** Get a boolean value indicating whether a voice is included in the list of known voices.
     * @param voiceName The name of the voice to check.
     * @returns `true` if the voiceName is known; `false` otherwise.
     */
    isKnownVoice(voiceName: string): boolean {
        return voiceName && allVoices.some(v => v.name === voiceName);
    }
};
