import { PricingBucket, SpeechModel, VoiceData } from "./types";

/** Accounting specifics paired with a SpeechModel. */
type VoiceCategory = {
    speechModel: SpeechModel;
    bucket: PricingBucket;
    /** `true` to count the billing units by bytes; `false` to count them by character. */
    countBytes: boolean;
};

// Generated from https://cloud.google.com/text-to-speech/pricing?hl=en
const categories: ReadonlyArray<VoiceCategory> = [
    // TODO: the Casual voice is a preview, no clue which bucket it's in
    { speechModel: "Casual", bucket: "Studio", countBytes: true },
    { speechModel: "Journey", bucket: "Journey", countBytes: true },
    { speechModel: "Neural", bucket: "Neural", countBytes: true },
    { speechModel: "News", bucket: "Studio", countBytes: true },
    { speechModel: "Polyglot", bucket: "Polyglot", countBytes: true },
    { speechModel: "Standard", bucket: "Standard", countBytes: false },
    { speechModel: "Studio", bucket: "Studio", countBytes: true },
    { speechModel: "Wavenet", bucket: "Wavenet", countBytes: false },
];

// Generated from https://cloud.google.com/text-to-speech/docs/voices
const allVoices: ReadonlyArray<VoiceData> = [
    { name: "af-ZA-Standard-A", language: "Afrikaans (South Africa) | Female" },
    { name: "ar-XA-Standard-A", language: "Arabic | Female" },
    { name: "ar-XA-Standard-B", language: "Arabic | Male" },
    { name: "ar-XA-Standard-C", language: "Arabic | Male" },
    { name: "ar-XA-Standard-D", language: "Arabic | Female" },
    { name: "ar-XA-Wavenet-A", language: "Arabic | Female" },
    { name: "ar-XA-Wavenet-B", language: "Arabic | Male" },
    { name: "ar-XA-Wavenet-C", language: "Arabic | Male" },
    { name: "ar-XA-Wavenet-D", language: "Arabic | Female" },
    { name: "eu-ES-Standard-A", language: "Basque (Spain) | Female" },
    { name: "eu-ES-Standard-B", language: "Basque (Spain) | Female" },
    { name: "bn-IN-Standard-A", language: "Bengali (India) | Female" },
    { name: "bn-IN-Standard-B", language: "Bengali (India) | Male" },
    { name: "bn-IN-Standard-C", language: "Bengali (India) | Female" },
    { name: "bn-IN-Standard-D", language: "Bengali (India) | Male" },
    { name: "bn-IN-Wavenet-A", language: "Bengali (India) | Female" },
    { name: "bn-IN-Wavenet-B", language: "Bengali (India) | Male" },
    { name: "bn-IN-Wavenet-C", language: "Bengali (India) | Female" },
    { name: "bn-IN-Wavenet-D", language: "Bengali (India) | Male" },
    { name: "bg-BG-Standard-A", language: "Bulgarian (Bulgaria) | Female" },
    { name: "bg-BG-Standard-B", language: "Bulgarian (Bulgaria) | Female" },
    { name: "ca-ES-Standard-A", language: "Catalan (Spain) | Female" },
    { name: "ca-ES-Standard-B", language: "Catalan (Spain) | Female" },
    { name: "yue-HK-Standard-A", language: "Chinese (Hong Kong) | Female" },
    { name: "yue-HK-Standard-B", language: "Chinese (Hong Kong) | Male" },
    { name: "yue-HK-Standard-C", language: "Chinese (Hong Kong) | Female" },
    { name: "yue-HK-Standard-D", language: "Chinese (Hong Kong) | Male" },
    { name: "cs-CZ-Standard-A", language: "Czech (Czech Republic) | Female" },
    { name: "cs-CZ-Standard-B", language: "Czech (Czech Republic) | Female" },
    { name: "cs-CZ-Wavenet-A", language: "Czech (Czech Republic) | Female" },
    { name: "da-DK-Neural2-D", language: "Danish (Denmark) | Female" },
    { name: "da-DK-Standard-A", language: "Danish (Denmark) | Female" },
    { name: "da-DK-Standard-C", language: "Danish (Denmark) | Male" },
    { name: "da-DK-Standard-D", language: "Danish (Denmark) | Female" },
    { name: "da-DK-Standard-E", language: "Danish (Denmark) | Female" },
    { name: "da-DK-Standard-F", language: "Danish (Denmark) | Female" },
    { name: "da-DK-Standard-G", language: "Danish (Denmark) | Male" },
    { name: "da-DK-Wavenet-A", language: "Danish (Denmark) | Female" },
    { name: "da-DK-Wavenet-C", language: "Danish (Denmark) | Male" },
    { name: "da-DK-Wavenet-D", language: "Danish (Denmark) | Female" },
    { name: "da-DK-Wavenet-E", language: "Danish (Denmark) | Female" },
    { name: "nl-BE-Standard-A", language: "Dutch (Belgium) | Female" },
    { name: "nl-BE-Standard-B", language: "Dutch (Belgium) | Male" },
    { name: "nl-BE-Standard-C", language: "Dutch (Belgium) | Female" },
    { name: "nl-BE-Standard-D", language: "Dutch (Belgium) | Male" },
    { name: "nl-BE-Wavenet-A", language: "Dutch (Belgium) | Female" },
    { name: "nl-BE-Wavenet-B", language: "Dutch (Belgium) | Male" },
    { name: "nl-NL-Standard-A", language: "Dutch (Netherlands) | Female" },
    { name: "nl-NL-Standard-B", language: "Dutch (Netherlands) | Male" },
    { name: "nl-NL-Standard-C", language: "Dutch (Netherlands) | Male" },
    { name: "nl-NL-Standard-D", language: "Dutch (Netherlands) | Female" },
    { name: "nl-NL-Standard-E", language: "Dutch (Netherlands) | Female" },
    { name: "nl-NL-Standard-F", language: "Dutch (Netherlands) | Female" },
    { name: "nl-NL-Standard-G", language: "Dutch (Netherlands) | Male" },
    { name: "nl-NL-Wavenet-A", language: "Dutch (Netherlands) | Female" },
    { name: "nl-NL-Wavenet-B", language: "Dutch (Netherlands) | Male" },
    { name: "nl-NL-Wavenet-C", language: "Dutch (Netherlands) | Male" },
    { name: "nl-NL-Wavenet-D", language: "Dutch (Netherlands) | Female" },
    { name: "nl-NL-Wavenet-E", language: "Dutch (Netherlands) | Female" },
    { name: "en-AU-Journey-D", language: "English (Australia) | Male" },
    { name: "en-AU-Journey-F", language: "English (Australia) | Female" },
    { name: "en-AU-Journey-O", language: "English (Australia) | Female" },
    { name: "en-AU-Neural2-A", language: "English (Australia) | Female" },
    { name: "en-AU-Neural2-B", language: "English (Australia) | Male" },
    { name: "en-AU-Neural2-C", language: "English (Australia) | Female" },
    { name: "en-AU-Neural2-D", language: "English (Australia) | Male" },
    { name: "en-AU-News-E", language: "English (Australia) | Female" },
    { name: "en-AU-News-F", language: "English (Australia) | Female" },
    { name: "en-AU-News-G", language: "English (Australia) | Male" },
    { name: "en-AU-Polyglot-1", language: "English (Australia) | Male" },
    { name: "en-AU-Standard-A", language: "English (Australia) | Female" },
    { name: "en-AU-Standard-B", language: "English (Australia) | Male" },
    { name: "en-AU-Standard-C", language: "English (Australia) | Female" },
    { name: "en-AU-Standard-D", language: "English (Australia) | Male" },
    { name: "en-AU-Wavenet-A", language: "English (Australia) | Female" },
    { name: "en-AU-Wavenet-B", language: "English (Australia) | Male" },
    { name: "en-AU-Wavenet-C", language: "English (Australia) | Female" },
    { name: "en-AU-Wavenet-D", language: "English (Australia) | Male" },
    { name: "en-IN-Journey-D", language: "English (India) | Male" },
    { name: "en-IN-Journey-F", language: "English (India) | Female" },
    { name: "en-IN-Journey-O", language: "English (India) | Female" },
    { name: "en-IN-Neural2-A", language: "English (India) | Female" },
    { name: "en-IN-Neural2-B", language: "English (India) | Male" },
    { name: "en-IN-Neural2-C", language: "English (India) | Male" },
    { name: "en-IN-Neural2-D", language: "English (India) | Female" },
    { name: "en-IN-Standard-A", language: "English (India) | Female" },
    { name: "en-IN-Standard-B", language: "English (India) | Male" },
    { name: "en-IN-Standard-C", language: "English (India) | Male" },
    { name: "en-IN-Standard-D", language: "English (India) | Female" },
    { name: "en-IN-Standard-E", language: "English (India) | Female" },
    { name: "en-IN-Standard-F", language: "English (India) | Male" },
    { name: "en-IN-Wavenet-A", language: "English (India) | Female" },
    { name: "en-IN-Wavenet-B", language: "English (India) | Male" },
    { name: "en-IN-Wavenet-C", language: "English (India) | Male" },
    { name: "en-IN-Wavenet-D", language: "English (India) | Female" },
    { name: "en-IN-Wavenet-E", language: "English (India) | Female" },
    { name: "en-IN-Wavenet-F", language: "English (India) | Male" },
    { name: "en-GB-Journey-D", language: "English (UK) | Male" },
    { name: "en-GB-Journey-F", language: "English (UK) | Female" },
    { name: "en-GB-Journey-O", language: "English (UK) | Female" },
    { name: "en-GB-Neural2-A", language: "English (UK) | Female" },
    { name: "en-GB-Neural2-B", language: "English (UK) | Male" },
    { name: "en-GB-Neural2-C", language: "English (UK) | Female" },
    { name: "en-GB-Neural2-D", language: "English (UK) | Male" },
    { name: "en-GB-Neural2-F", language: "English (UK) | Female" },
    { name: "en-GB-News-G", language: "English (UK) | Female" },
    { name: "en-GB-News-H", language: "English (UK) | Female" },
    { name: "en-GB-News-I", language: "English (UK) | Female" },
    { name: "en-GB-News-J", language: "English (UK) | Male" },
    { name: "en-GB-News-K", language: "English (UK) | Male" },
    { name: "en-GB-News-L", language: "English (UK) | Male" },
    { name: "en-GB-News-M", language: "English (UK) | Male" },
    { name: "en-GB-Standard-A", language: "English (UK) | Female" },
    { name: "en-GB-Standard-B", language: "English (UK) | Male" },
    { name: "en-GB-Standard-C", language: "English (UK) | Female" },
    { name: "en-GB-Standard-D", language: "English (UK) | Male" },
    { name: "en-GB-Standard-F", language: "English (UK) | Female" },
    { name: "en-GB-Standard-N", language: "English (UK) | Female" },
    { name: "en-GB-Standard-O", language: "English (UK) | Male" },
    { name: "en-GB-Studio-B", language: "English (UK) | Male" },
    { name: "en-GB-Studio-C", language: "English (UK) | Female" },
    { name: "en-GB-Wavenet-A", language: "English (UK) | Female" },
    { name: "en-GB-Wavenet-B", language: "English (UK) | Male" },
    { name: "en-GB-Wavenet-C", language: "English (UK) | Female" },
    { name: "en-GB-Wavenet-D", language: "English (UK) | Male" },
    { name: "en-GB-Wavenet-F", language: "English (UK) | Female" },
    { name: "en-US-Casual-K", language: "English (US) | Male" },
    { name: "en-US-Journey-D", language: "English (US) | Male" },
    { name: "en-US-Journey-F", language: "English (US) | Female" },
    { name: "en-US-Journey-O", language: "English (US) | Female" },
    { name: "en-US-Neural2-A", language: "English (US) | Male" },
    { name: "en-US-Neural2-C", language: "English (US) | Female" },
    { name: "en-US-Neural2-D", language: "English (US) | Male" },
    { name: "en-US-Neural2-E", language: "English (US) | Female" },
    { name: "en-US-Neural2-F", language: "English (US) | Female" },
    { name: "en-US-Neural2-G", language: "English (US) | Female" },
    { name: "en-US-Neural2-H", language: "English (US) | Female" },
    { name: "en-US-Neural2-I", language: "English (US) | Male" },
    { name: "en-US-Neural2-J", language: "English (US) | Male" },
    { name: "en-US-News-K", language: "English (US) | Female" },
    { name: "en-US-News-L", language: "English (US) | Female" },
    { name: "en-US-News-N", language: "English (US) | Male" },
    { name: "en-US-Polyglot-1", language: "English (US) | Male" },
    { name: "en-US-Standard-A", language: "English (US) | Male" },
    { name: "en-US-Standard-B", language: "English (US) | Male" },
    { name: "en-US-Standard-C", language: "English (US) | Female" },
    { name: "en-US-Standard-D", language: "English (US) | Male" },
    { name: "en-US-Standard-E", language: "English (US) | Female" },
    { name: "en-US-Standard-F", language: "English (US) | Female" },
    { name: "en-US-Standard-G", language: "English (US) | Female" },
    { name: "en-US-Standard-H", language: "English (US) | Female" },
    { name: "en-US-Standard-I", language: "English (US) | Male" },
    { name: "en-US-Standard-J", language: "English (US) | Male" },
    { name: "en-US-Studio-O", language: "English (US) | Female" },
    { name: "en-US-Studio-Q", language: "English (US) | Male" },
    { name: "en-US-Wavenet-A", language: "English (US) | Male" },
    { name: "en-US-Wavenet-B", language: "English (US) | Male" },
    { name: "en-US-Wavenet-C", language: "English (US) | Female" },
    { name: "en-US-Wavenet-D", language: "English (US) | Male" },
    { name: "en-US-Wavenet-E", language: "English (US) | Female" },
    { name: "en-US-Wavenet-F", language: "English (US) | Female" },
    { name: "en-US-Wavenet-G", language: "English (US) | Female" },
    { name: "en-US-Wavenet-H", language: "English (US) | Female" },
    { name: "en-US-Wavenet-I", language: "English (US) | Male" },
    { name: "en-US-Wavenet-J", language: "English (US) | Male" },
    { name: "fil-PH-Standard-A", language: "Filipino (Philippines) | Female" },
    { name: "fil-PH-Standard-B", language: "Filipino (Philippines) | Female" },
    { name: "fil-PH-Standard-C", language: "Filipino (Philippines) | Male" },
    { name: "fil-PH-Standard-D", language: "Filipino (Philippines) | Male" },
    { name: "fil-PH-Wavenet-A", language: "Filipino (Philippines) | Female" },
    { name: "fil-PH-Wavenet-B", language: "Filipino (Philippines) | Female" },
    { name: "fil-PH-Wavenet-C", language: "Filipino (Philippines) | Male" },
    { name: "fil-PH-Wavenet-D", language: "Filipino (Philippines) | Male" },
    { name: "fil-ph-Neural2-A", language: "Filipino (Philippines) | Female" },
    { name: "fil-ph-Neural2-D", language: "Filipino (Philippines) | Male" },
    { name: "fi-FI-Standard-A", language: "Finnish (Finland) | Female" },
    { name: "fi-FI-Standard-B", language: "Finnish (Finland) | Female" },
    { name: "fi-FI-Wavenet-A", language: "Finnish (Finland) | Female" },
    { name: "fr-CA-Journey-D", language: "French (Canada) | Male" },
    { name: "fr-CA-Journey-F", language: "French (Canada) | Female" },
    { name: "fr-CA-Journey-O", language: "French (Canada) | Female" },
    { name: "fr-CA-Neural2-A", language: "French (Canada) | Female" },
    { name: "fr-CA-Neural2-B", language: "French (Canada) | Male" },
    { name: "fr-CA-Neural2-C", language: "French (Canada) | Female" },
    { name: "fr-CA-Neural2-D", language: "French (Canada) | Male" },
    { name: "fr-CA-Standard-A", language: "French (Canada) | Female" },
    { name: "fr-CA-Standard-B", language: "French (Canada) | Male" },
    { name: "fr-CA-Standard-C", language: "French (Canada) | Female" },
    { name: "fr-CA-Standard-D", language: "French (Canada) | Male" },
    { name: "fr-CA-Wavenet-A", language: "French (Canada) | Female" },
    { name: "fr-CA-Wavenet-B", language: "French (Canada) | Male" },
    { name: "fr-CA-Wavenet-C", language: "French (Canada) | Female" },
    { name: "fr-CA-Wavenet-D", language: "French (Canada) | Male" },
    { name: "fr-FR-Journey-D", language: "French (France) | Male" },
    { name: "fr-FR-Journey-F", language: "French (France) | Female" },
    { name: "fr-FR-Journey-O", language: "French (France) | Female" },
    { name: "fr-FR-Neural2-A", language: "French (France) | Female" },
    { name: "fr-FR-Neural2-B", language: "French (France) | Male" },
    { name: "fr-FR-Neural2-C", language: "French (France) | Female" },
    { name: "fr-FR-Neural2-D", language: "French (France) | Male" },
    { name: "fr-FR-Neural2-E", language: "French (France) | Female" },
    { name: "fr-FR-Polyglot-1", language: "French (France) | Male" },
    { name: "fr-FR-Standard-A", language: "French (France) | Female" },
    { name: "fr-FR-Standard-B", language: "French (France) | Male" },
    { name: "fr-FR-Standard-C", language: "French (France) | Female" },
    { name: "fr-FR-Standard-D", language: "French (France) | Male" },
    { name: "fr-FR-Standard-E", language: "French (France) | Female" },
    { name: "fr-FR-Standard-F", language: "French (France) | Female" },
    { name: "fr-FR-Standard-G", language: "French (France) | Male" },
    { name: "fr-FR-Studio-A", language: "French (France) | Female" },
    { name: "fr-FR-Studio-D", language: "French (France) | Male" },
    { name: "fr-FR-Wavenet-A", language: "French (France) | Female" },
    { name: "fr-FR-Wavenet-B", language: "French (France) | Male" },
    { name: "fr-FR-Wavenet-C", language: "French (France) | Female" },
    { name: "fr-FR-Wavenet-D", language: "French (France) | Male" },
    { name: "fr-FR-Wavenet-E", language: "French (France) | Female" },
    { name: "fr-FR-Wavenet-F", language: "French (France) | Female" },
    { name: "fr-FR-Wavenet-G", language: "French (France) | Male" },
    { name: "gl-ES-Standard-A", language: "Galician (Spain) | Female" },
    { name: "gl-ES-Standard-B", language: "Galician (Spain) | Female" },
    { name: "de-DE-Journey-D", language: "German (Germany) | Male" },
    { name: "de-DE-Journey-F", language: "German (Germany) | Female" },
    { name: "de-DE-Journey-O", language: "German (Germany) | Female" },
    { name: "de-DE-Neural2-A", language: "German (Germany) | Female" },
    { name: "de-DE-Neural2-B", language: "German (Germany) | Male" },
    { name: "de-DE-Neural2-C", language: "German (Germany) | Female" },
    { name: "de-DE-Neural2-D", language: "German (Germany) | Male" },
    { name: "de-DE-Neural2-F", language: "German (Germany) | Female" },
    { name: "de-DE-Polyglot-1", language: "German (Germany) | Male" },
    { name: "de-DE-Standard-A", language: "German (Germany) | Female" },
    { name: "de-DE-Standard-B", language: "German (Germany) | Male" },
    { name: "de-DE-Standard-C", language: "German (Germany) | Female" },
    { name: "de-DE-Standard-D", language: "German (Germany) | Male" },
    { name: "de-DE-Standard-E", language: "German (Germany) | Male" },
    { name: "de-DE-Standard-F", language: "German (Germany) | Female" },
    { name: "de-DE-Standard-G", language: "German (Germany) | Female" },
    { name: "de-DE-Standard-H", language: "German (Germany) | Male" },
    { name: "de-DE-Studio-B", language: "German (Germany) | Male" },
    { name: "de-DE-Studio-C", language: "German (Germany) | Female" },
    { name: "de-DE-Wavenet-A", language: "German (Germany) | Female" },
    { name: "de-DE-Wavenet-B", language: "German (Germany) | Male" },
    { name: "de-DE-Wavenet-C", language: "German (Germany) | Female" },
    { name: "de-DE-Wavenet-D", language: "German (Germany) | Male" },
    { name: "de-DE-Wavenet-E", language: "German (Germany) | Male" },
    { name: "de-DE-Wavenet-F", language: "German (Germany) | Female" },
    { name: "de-DE-Wavenet-G", language: "German (Germany) | Female" },
    { name: "de-DE-Wavenet-H", language: "German (Germany) | Male" },
    { name: "el-GR-Standard-A", language: "Greek (Greece) | Female" },
    { name: "el-GR-Standard-B", language: "Greek (Greece) | Female" },
    { name: "el-GR-Wavenet-A", language: "Greek (Greece) | Female" },
    { name: "gu-IN-Standard-A", language: "Gujarati (India) | Female" },
    { name: "gu-IN-Standard-B", language: "Gujarati (India) | Male" },
    { name: "gu-IN-Standard-C", language: "Gujarati (India) | Female" },
    { name: "gu-IN-Standard-D", language: "Gujarati (India) | Male" },
    { name: "gu-IN-Wavenet-A", language: "Gujarati (India) | Female" },
    { name: "gu-IN-Wavenet-B", language: "Gujarati (India) | Male" },
    { name: "gu-IN-Wavenet-C", language: "Gujarati (India) | Female" },
    { name: "gu-IN-Wavenet-D", language: "Gujarati (India) | Male" },
    { name: "he-IL-Standard-A", language: "Hebrew (Israel) | Female" },
    { name: "he-IL-Standard-B", language: "Hebrew (Israel) | Male" },
    { name: "he-IL-Standard-C", language: "Hebrew (Israel) | Female" },
    { name: "he-IL-Standard-D", language: "Hebrew (Israel) | Male" },
    { name: "he-IL-Wavenet-A", language: "Hebrew (Israel) | Female" },
    { name: "he-IL-Wavenet-B", language: "Hebrew (Israel) | Male" },
    { name: "he-IL-Wavenet-C", language: "Hebrew (Israel) | Female" },
    { name: "he-IL-Wavenet-D", language: "Hebrew (Israel) | Male" },
    { name: "hi-IN-Neural2-A", language: "Hindi (India) | Female" },
    { name: "hi-IN-Neural2-B", language: "Hindi (India) | Male" },
    { name: "hi-IN-Neural2-C", language: "Hindi (India) | Male" },
    { name: "hi-IN-Neural2-D", language: "Hindi (India) | Female" },
    { name: "hi-IN-Standard-A", language: "Hindi (India) | Female" },
    { name: "hi-IN-Standard-B", language: "Hindi (India) | Male" },
    { name: "hi-IN-Standard-C", language: "Hindi (India) | Male" },
    { name: "hi-IN-Standard-D", language: "Hindi (India) | Female" },
    { name: "hi-IN-Standard-E", language: "Hindi (India) | Female" },
    { name: "hi-IN-Standard-F", language: "Hindi (India) | Male" },
    { name: "hi-IN-Wavenet-A", language: "Hindi (India) | Female" },
    { name: "hi-IN-Wavenet-B", language: "Hindi (India) | Male" },
    { name: "hi-IN-Wavenet-C", language: "Hindi (India) | Male" },
    { name: "hi-IN-Wavenet-D", language: "Hindi (India) | Female" },
    { name: "hi-IN-Wavenet-E", language: "Hindi (India) | Female" },
    { name: "hi-IN-Wavenet-F", language: "Hindi (India) | Male" },
    { name: "hu-HU-Standard-A", language: "Hungarian (Hungary) | Female" },
    { name: "hu-HU-Standard-B", language: "Hungarian (Hungary) | Female" },
    { name: "hu-HU-Wavenet-A", language: "Hungarian (Hungary) | Female" },
    { name: "is-IS-Standard-A", language: "Icelandic (Iceland) | Female" },
    { name: "is-IS-Standard-B", language: "Icelandic (Iceland) | Female" },
    { name: "id-ID-Standard-A", language: "Indonesian (Indonesia) | Female" },
    { name: "id-ID-Standard-B", language: "Indonesian (Indonesia) | Male" },
    { name: "id-ID-Standard-C", language: "Indonesian (Indonesia) | Male" },
    { name: "id-ID-Standard-D", language: "Indonesian (Indonesia) | Female" },
    { name: "id-ID-Wavenet-A", language: "Indonesian (Indonesia) | Female" },
    { name: "id-ID-Wavenet-B", language: "Indonesian (Indonesia) | Male" },
    { name: "id-ID-Wavenet-C", language: "Indonesian (Indonesia) | Male" },
    { name: "id-ID-Wavenet-D", language: "Indonesian (Indonesia) | Female" },
    { name: "it-IT-Journey-D", language: "Italian (Italy) | Male" },
    { name: "it-IT-Journey-F", language: "Italian (Italy) | Female" },
    { name: "it-IT-Journey-O", language: "Italian (Italy) | Female" },
    { name: "it-IT-Neural2-A", language: "Italian (Italy) | Female" },
    { name: "it-IT-Neural2-C", language: "Italian (Italy) | Male" },
    { name: "it-IT-Standard-A", language: "Italian (Italy) | Female" },
    { name: "it-IT-Standard-B", language: "Italian (Italy) | Female" },
    { name: "it-IT-Standard-C", language: "Italian (Italy) | Male" },
    { name: "it-IT-Standard-D", language: "Italian (Italy) | Male" },
    { name: "it-IT-Standard-E", language: "Italian (Italy) | Female" },
    { name: "it-IT-Standard-F", language: "Italian (Italy) | Male" },
    { name: "it-IT-Wavenet-A", language: "Italian (Italy) | Female" },
    { name: "it-IT-Wavenet-B", language: "Italian (Italy) | Female" },
    { name: "it-IT-Wavenet-C", language: "Italian (Italy) | Male" },
    { name: "it-IT-Wavenet-D", language: "Italian (Italy) | Male" },
    { name: "ja-JP-Neural2-B", language: "Japanese (Japan) | Female" },
    { name: "ja-JP-Neural2-C", language: "Japanese (Japan) | Male" },
    { name: "ja-JP-Neural2-D", language: "Japanese (Japan) | Male" },
    { name: "ja-JP-Standard-A", language: "Japanese (Japan) | Female" },
    { name: "ja-JP-Standard-B", language: "Japanese (Japan) | Female" },
    { name: "ja-JP-Standard-C", language: "Japanese (Japan) | Male" },
    { name: "ja-JP-Standard-D", language: "Japanese (Japan) | Male" },
    { name: "ja-JP-Wavenet-A", language: "Japanese (Japan) | Female" },
    { name: "ja-JP-Wavenet-B", language: "Japanese (Japan) | Female" },
    { name: "ja-JP-Wavenet-C", language: "Japanese (Japan) | Male" },
    { name: "ja-JP-Wavenet-D", language: "Japanese (Japan) | Male" },
    { name: "kn-IN-Standard-A", language: "Kannada (India) | Female" },
    { name: "kn-IN-Standard-B", language: "Kannada (India) | Male" },
    { name: "kn-IN-Standard-C", language: "Kannada (India) | Female" },
    { name: "kn-IN-Standard-D", language: "Kannada (India) | Male" },
    { name: "kn-IN-Wavenet-A", language: "Kannada (India) | Female" },
    { name: "kn-IN-Wavenet-B", language: "Kannada (India) | Male" },
    { name: "kn-IN-Wavenet-C", language: "Kannada (India) | Female" },
    { name: "kn-IN-Wavenet-D", language: "Kannada (India) | Male" },
    { name: "ko-KR-Neural2-A", language: "Korean (South Korea) | Female" },
    { name: "ko-KR-Neural2-B", language: "Korean (South Korea) | Female" },
    { name: "ko-KR-Neural2-C", language: "Korean (South Korea) | Male" },
    { name: "ko-KR-Standard-A", language: "Korean (South Korea) | Female" },
    { name: "ko-KR-Standard-B", language: "Korean (South Korea) | Female" },
    { name: "ko-KR-Standard-C", language: "Korean (South Korea) | Male" },
    { name: "ko-KR-Standard-D", language: "Korean (South Korea) | Male" },
    { name: "ko-KR-Wavenet-A", language: "Korean (South Korea) | Female" },
    { name: "ko-KR-Wavenet-B", language: "Korean (South Korea) | Female" },
    { name: "ko-KR-Wavenet-C", language: "Korean (South Korea) | Male" },
    { name: "ko-KR-Wavenet-D", language: "Korean (South Korea) | Male" },
    { name: "lv-LV-Standard-A", language: "Latvian (Latvia) | Male" },
    { name: "lv-LV-Standard-B", language: "Latvian (Latvia) | Male" },
    { name: "lt-LT-Standard-A", language: "Lithuanian (Lithuania) | Male" },
    { name: "lt-LT-Standard-B", language: "Lithuanian (Lithuania) | Male" },
    { name: "ms-MY-Standard-A", language: "Malay (Malaysia) | Female" },
    { name: "ms-MY-Standard-B", language: "Malay (Malaysia) | Male" },
    { name: "ms-MY-Standard-C", language: "Malay (Malaysia) | Female" },
    { name: "ms-MY-Standard-D", language: "Malay (Malaysia) | Male" },
    { name: "ms-MY-Wavenet-A", language: "Malay (Malaysia) | Female" },
    { name: "ms-MY-Wavenet-B", language: "Malay (Malaysia) | Male" },
    { name: "ms-MY-Wavenet-C", language: "Malay (Malaysia) | Female" },
    { name: "ms-MY-Wavenet-D", language: "Malay (Malaysia) | Male" },
    { name: "ml-IN-Standard-A", language: "Malayalam (India) | Female" },
    { name: "ml-IN-Standard-B", language: "Malayalam (India) | Male" },
    { name: "ml-IN-Standard-C", language: "Malayalam (India) | Female" },
    { name: "ml-IN-Standard-D", language: "Malayalam (India) | Male" },
    { name: "ml-IN-Wavenet-A", language: "Malayalam (India) | Female" },
    { name: "ml-IN-Wavenet-B", language: "Malayalam (India) | Male" },
    { name: "ml-IN-Wavenet-C", language: "Malayalam (India) | Female" },
    { name: "ml-IN-Wavenet-D", language: "Malayalam (India) | Male" },
    { name: "cmn-CN-Standard-A", language: "Mandarin Chinese | Female" },
    { name: "cmn-CN-Standard-B", language: "Mandarin Chinese | Male" },
    { name: "cmn-CN-Standard-C", language: "Mandarin Chinese | Male" },
    { name: "cmn-CN-Standard-D", language: "Mandarin Chinese | Female" },
    { name: "cmn-CN-Wavenet-A", language: "Mandarin Chinese | Female" },
    { name: "cmn-CN-Wavenet-B", language: "Mandarin Chinese | Male" },
    { name: "cmn-CN-Wavenet-C", language: "Mandarin Chinese | Male" },
    { name: "cmn-CN-Wavenet-D", language: "Mandarin Chinese | Female" },
    { name: "cmn-TW-Standard-A", language: "Mandarin Chinese | Female" },
    { name: "cmn-TW-Standard-B", language: "Mandarin Chinese | Male" },
    { name: "cmn-TW-Standard-C", language: "Mandarin Chinese | Male" },
    { name: "cmn-TW-Wavenet-A", language: "Mandarin Chinese | Female" },
    { name: "cmn-TW-Wavenet-B", language: "Mandarin Chinese | Male" },
    { name: "cmn-TW-Wavenet-C", language: "Mandarin Chinese | Male" },
    { name: "mr-IN-Standard-A", language: "Marathi (India) | Female" },
    { name: "mr-IN-Standard-B", language: "Marathi (India) | Male" },
    { name: "mr-IN-Standard-C", language: "Marathi (India) | Female" },
    { name: "mr-IN-Wavenet-A", language: "Marathi (India) | Female" },
    { name: "mr-IN-Wavenet-B", language: "Marathi (India) | Male" },
    { name: "mr-IN-Wavenet-C", language: "Marathi (India) | Female" },
    { name: "nb-NO-Standard-A", language: "Norwegian (Norway) | Female" },
    { name: "nb-NO-Standard-B", language: "Norwegian (Norway) | Male" },
    { name: "nb-NO-Standard-C", language: "Norwegian (Norway) | Female" },
    { name: "nb-NO-Standard-D", language: "Norwegian (Norway) | Male" },
    { name: "nb-NO-Standard-E", language: "Norwegian (Norway) | Female" },
    { name: "nb-NO-Standard-F", language: "Norwegian (Norway) | Female" },
    { name: "nb-NO-Standard-G", language: "Norwegian (Norway) | Male" },
    { name: "nb-NO-Wavenet-A", language: "Norwegian (Norway) | Female" },
    { name: "nb-NO-Wavenet-B", language: "Norwegian (Norway) | Male" },
    { name: "nb-NO-Wavenet-C", language: "Norwegian (Norway) | Female" },
    { name: "nb-NO-Wavenet-D", language: "Norwegian (Norway) | Male" },
    { name: "nb-NO-Wavenet-E", language: "Norwegian (Norway) | Female" },
    { name: "pl-PL-Standard-A", language: "Polish (Poland) | Female" },
    { name: "pl-PL-Standard-B", language: "Polish (Poland) | Male" },
    { name: "pl-PL-Standard-C", language: "Polish (Poland) | Male" },
    { name: "pl-PL-Standard-D", language: "Polish (Poland) | Female" },
    { name: "pl-PL-Standard-E", language: "Polish (Poland) | Female" },
    { name: "pl-PL-Standard-F", language: "Polish (Poland) | Female" },
    { name: "pl-PL-Standard-G", language: "Polish (Poland) | Male" },
    { name: "pl-PL-Wavenet-A", language: "Polish (Poland) | Female" },
    { name: "pl-PL-Wavenet-B", language: "Polish (Poland) | Male" },
    { name: "pl-PL-Wavenet-C", language: "Polish (Poland) | Male" },
    { name: "pl-PL-Wavenet-D", language: "Polish (Poland) | Female" },
    { name: "pl-PL-Wavenet-E", language: "Polish (Poland) | Female" },
    { name: "pt-BR-Neural2-A", language: "Portuguese (Brazil) | Female" },
    { name: "pt-BR-Neural2-B", language: "Portuguese (Brazil) | Male" },
    { name: "pt-BR-Neural2-C", language: "Portuguese (Brazil) | Female" },
    { name: "pt-BR-Standard-A", language: "Portuguese (Brazil) | Female" },
    { name: "pt-BR-Standard-B", language: "Portuguese (Brazil) | Male" },
    { name: "pt-BR-Standard-C", language: "Portuguese (Brazil) | Female" },
    { name: "pt-BR-Standard-D", language: "Portuguese (Brazil) | Female" },
    { name: "pt-BR-Standard-E", language: "Portuguese (Brazil) | Male" },
    { name: "pt-BR-Wavenet-A", language: "Portuguese (Brazil) | Female" },
    { name: "pt-BR-Wavenet-B", language: "Portuguese (Brazil) | Male" },
    { name: "pt-BR-Wavenet-C", language: "Portuguese (Brazil) | Female" },
    { name: "pt-BR-Wavenet-D", language: "Portuguese (Brazil) | Female" },
    { name: "pt-BR-Wavenet-E", language: "Portuguese (Brazil) | Male" },
    { name: "pt-PT-Standard-A", language: "Portuguese (Portugal) | Female" },
    { name: "pt-PT-Standard-B", language: "Portuguese (Portugal) | Male" },
    { name: "pt-PT-Standard-C", language: "Portuguese (Portugal) | Male" },
    { name: "pt-PT-Standard-D", language: "Portuguese (Portugal) | Female" },
    { name: "pt-PT-Standard-E", language: "Portuguese (Portugal) | Female" },
    { name: "pt-PT-Standard-F", language: "Portuguese (Portugal) | Male" },
    { name: "pt-PT-Wavenet-A", language: "Portuguese (Portugal) | Female" },
    { name: "pt-PT-Wavenet-B", language: "Portuguese (Portugal) | Male" },
    { name: "pt-PT-Wavenet-C", language: "Portuguese (Portugal) | Male" },
    { name: "pt-PT-Wavenet-D", language: "Portuguese (Portugal) | Female" },
    { name: "pa-IN-Standard-A", language: "Punjabi (India) | Female" },
    { name: "pa-IN-Standard-B", language: "Punjabi (India) | Male" },
    { name: "pa-IN-Standard-C", language: "Punjabi (India) | Female" },
    { name: "pa-IN-Standard-D", language: "Punjabi (India) | Male" },
    { name: "pa-IN-Wavenet-A", language: "Punjabi (India) | Female" },
    { name: "pa-IN-Wavenet-B", language: "Punjabi (India) | Male" },
    { name: "pa-IN-Wavenet-C", language: "Punjabi (India) | Female" },
    { name: "pa-IN-Wavenet-D", language: "Punjabi (India) | Male" },
    { name: "ro-RO-Standard-A", language: "Romanian (Romania) | Female" },
    { name: "ro-RO-Standard-B", language: "Romanian (Romania) | Female" },
    { name: "ro-RO-Wavenet-A", language: "Romanian (Romania) | Female" },
    { name: "ru-RU-Standard-A", language: "Russian (Russia) | Female" },
    { name: "ru-RU-Standard-B", language: "Russian (Russia) | Male" },
    { name: "ru-RU-Standard-C", language: "Russian (Russia) | Female" },
    { name: "ru-RU-Standard-D", language: "Russian (Russia) | Male" },
    { name: "ru-RU-Standard-E", language: "Russian (Russia) | Female" },
    { name: "ru-RU-Wavenet-A", language: "Russian (Russia) | Female" },
    { name: "ru-RU-Wavenet-B", language: "Russian (Russia) | Male" },
    { name: "ru-RU-Wavenet-C", language: "Russian (Russia) | Female" },
    { name: "ru-RU-Wavenet-D", language: "Russian (Russia) | Male" },
    { name: "ru-RU-Wavenet-E", language: "Russian (Russia) | Female" },
    { name: "sr-RS-Standard-A", language: "Serbian (Cyrillic) | Female" },
    { name: "sk-SK-Standard-A", language: "Slovak (Slovakia) | Female" },
    { name: "sk-SK-Standard-B", language: "Slovak (Slovakia) | Female" },
    { name: "sk-SK-Wavenet-A", language: "Slovak (Slovakia) | Female" },
    { name: "es-ES-Journey-D", language: "Spanish (Spain) | Male" },
    { name: "es-ES-Journey-F", language: "Spanish (Spain) | Female" },
    { name: "es-ES-Journey-O", language: "Spanish (Spain) | Female" },
    { name: "es-ES-Neural2-A", language: "Spanish (Spain) | Female" },
    { name: "es-ES-Neural2-B", language: "Spanish (Spain) | Male" },
    { name: "es-ES-Neural2-C", language: "Spanish (Spain) | Female" },
    { name: "es-ES-Neural2-D", language: "Spanish (Spain) | Female" },
    { name: "es-ES-Neural2-E", language: "Spanish (Spain) | Female" },
    { name: "es-ES-Neural2-F", language: "Spanish (Spain) | Male" },
    { name: "es-ES-Polyglot-1", language: "Spanish (Spain) | Male" },
    { name: "es-ES-Standard-A", language: "Spanish (Spain) | Female" },
    { name: "es-ES-Standard-B", language: "Spanish (Spain) | Male" },
    { name: "es-ES-Standard-C", language: "Spanish (Spain) | Female" },
    { name: "es-ES-Standard-D", language: "Spanish (Spain) | Female" },
    { name: "es-ES-Standard-E", language: "Spanish (Spain) | Male" },
    { name: "es-ES-Standard-F", language: "Spanish (Spain) | Female" },
    { name: "es-ES-Studio-C", language: "Spanish (Spain) | Female" },
    { name: "es-ES-Studio-F", language: "Spanish (Spain) | Male" },
    { name: "es-ES-Wavenet-B", language: "Spanish (Spain) | Male" },
    { name: "es-ES-Wavenet-C", language: "Spanish (Spain) | Female" },
    { name: "es-ES-Wavenet-D", language: "Spanish (Spain) | Female" },
    { name: "es-ES-Wavenet-E", language: "Spanish (Spain) | Male" },
    { name: "es-ES-Wavenet-F", language: "Spanish (Spain) | Female" },
    { name: "es-US-Journey-D", language: "Spanish (US) | Male" },
    { name: "es-US-Journey-F", language: "Spanish (US) | Female" },
    { name: "es-US-Journey-O", language: "Spanish (US) | Female" },
    { name: "es-US-Neural2-A", language: "Spanish (US) | Female" },
    { name: "es-US-Neural2-B", language: "Spanish (US) | Male" },
    { name: "es-US-Neural2-C", language: "Spanish (US) | Male" },
    { name: "es-US-News-D", language: "Spanish (US) | Male" },
    { name: "es-US-News-E", language: "Spanish (US) | Male" },
    { name: "es-US-News-F", language: "Spanish (US) | Female" },
    { name: "es-US-News-G", language: "Spanish (US) | Female" },
    { name: "es-US-Polyglot-1", language: "Spanish (US) | Male" },
    { name: "es-US-Standard-A", language: "Spanish (US) | Female" },
    { name: "es-US-Standard-B", language: "Spanish (US) | Male" },
    { name: "es-US-Standard-C", language: "Spanish (US) | Male" },
    { name: "es-US-Studio-B", language: "Spanish (US) | Male" },
    { name: "es-US-Wavenet-A", language: "Spanish (US) | Female" },
    { name: "es-US-Wavenet-B", language: "Spanish (US) | Male" },
    { name: "es-US-Wavenet-C", language: "Spanish (US) | Male" },
    { name: "sv-SE-Standard-A", language: "Swedish (Sweden) | Female" },
    { name: "sv-SE-Standard-B", language: "Swedish (Sweden) | Female" },
    { name: "sv-SE-Standard-C", language: "Swedish (Sweden) | Female" },
    { name: "sv-SE-Standard-D", language: "Swedish (Sweden) | Male" },
    { name: "sv-SE-Standard-E", language: "Swedish (Sweden) | Male" },
    { name: "sv-SE-Standard-F", language: "Swedish (Sweden) | Female" },
    { name: "sv-SE-Standard-G", language: "Swedish (Sweden) | Male" },
    { name: "sv-SE-Wavenet-A", language: "Swedish (Sweden) | Female" },
    { name: "sv-SE-Wavenet-B", language: "Swedish (Sweden) | Female" },
    { name: "sv-SE-Wavenet-C", language: "Swedish (Sweden) | Male" },
    { name: "sv-SE-Wavenet-D", language: "Swedish (Sweden) | Female" },
    { name: "sv-SE-Wavenet-E", language: "Swedish (Sweden) | Male" },
    { name: "ta-IN-Standard-A", language: "Tamil (India) | Female" },
    { name: "ta-IN-Standard-B", language: "Tamil (India) | Male" },
    { name: "ta-IN-Standard-C", language: "Tamil (India) | Female" },
    { name: "ta-IN-Standard-D", language: "Tamil (India) | Male" },
    { name: "ta-IN-Wavenet-A", language: "Tamil (India) | Female" },
    { name: "ta-IN-Wavenet-B", language: "Tamil (India) | Male" },
    { name: "ta-IN-Wavenet-C", language: "Tamil (India) | Female" },
    { name: "ta-IN-Wavenet-D", language: "Tamil (India) | Male" },
    { name: "te-IN-Standard-A", language: "Telugu (India) | Female" },
    { name: "te-IN-Standard-B", language: "Telugu (India) | Male" },
    { name: "te-IN-Standard-C", language: "Telugu (India) | Female" },
    { name: "te-IN-Standard-D", language: "Telugu (India) | Male" },
    { name: "th-TH-Neural2-C", language: "Thai (Thailand) | Female" },
    { name: "th-TH-Standard-A", language: "Thai (Thailand) | Female" },
    { name: "tr-TR-Standard-A", language: "Turkish (Turkey) | Female" },
    { name: "tr-TR-Standard-B", language: "Turkish (Turkey) | Male" },
    { name: "tr-TR-Standard-C", language: "Turkish (Turkey) | Female" },
    { name: "tr-TR-Standard-D", language: "Turkish (Turkey) | Female" },
    { name: "tr-TR-Standard-E", language: "Turkish (Turkey) | Male" },
    { name: "tr-TR-Wavenet-A", language: "Turkish (Turkey) | Female" },
    { name: "tr-TR-Wavenet-B", language: "Turkish (Turkey) | Male" },
    { name: "tr-TR-Wavenet-C", language: "Turkish (Turkey) | Female" },
    { name: "tr-TR-Wavenet-D", language: "Turkish (Turkey) | Female" },
    { name: "tr-TR-Wavenet-E", language: "Turkish (Turkey) | Male" },
    { name: "uk-UA-Standard-A", language: "Ukrainian (Ukraine) | Female" },
    { name: "uk-UA-Wavenet-A", language: "Ukrainian (Ukraine) | Female" },
    { name: "vi-VN-Neural2-A", language: "Vietnamese (Vietnam) | Female" },
    { name: "vi-VN-Neural2-D", language: "Vietnamese (Vietnam) | Male" },
    { name: "vi-VN-Standard-A", language: "Vietnamese (Vietnam) | Female" },
    { name: "vi-VN-Standard-B", language: "Vietnamese (Vietnam) | Male" },
    { name: "vi-VN-Standard-C", language: "Vietnamese (Vietnam) | Female" },
    { name: "vi-VN-Standard-D", language: "Vietnamese (Vietnam) | Male" },
    { name: "vi-VN-Wavenet-A", language: "Vietnamese (Vietnam) | Female" },
    { name: "vi-VN-Wavenet-B", language: "Vietnamese (Vietnam) | Male" },
    { name: "vi-VN-Wavenet-C", language: "Vietnamese (Vietnam) | Female" },
    { name: "vi-VN-Wavenet-D", language: "Vietnamese (Vietnam) | Male" },
];

function nonJourneyVoices() {
    return allVoices.filter(v => !v.name.includes("Journey"));
};

export default {
    /** Get an array of tuples of a SpeechModel paired with some accounting specifics. */
    getAllCategories: (): ReadonlyArray<VoiceCategory> => categories,
    /** Get an array of the names of all known pricing buckets. */
    getAllPricingBuckets: (): ReadonlyArray<PricingBucket> => categories.map(t => t.bucket).filter((v, n, a) => a.indexOf(v) === n),
    /** Get an array of all known speech synthesis voice models. */
    getAllSpeechModels: (): ReadonlyArray<SpeechModel> => categories.map(t => t.speechModel),
    /** Get an array of all of the voices supported by this plugin. */
    getSupportedVoices: (): ReadonlyArray<VoiceData> => nonJourneyVoices(),

    getVoiceCategory: (voiceName: string): VoiceCategory => {
        return categories.find(cat => voiceName?.includes(cat.speechModel)) ??
            { speechModel: "Unknown", bucket: "Unknown", countBytes: true };
    },
    getVoiceGender: (voiceName: string): "Male" | "Female" | null => {
        const langGender = allVoices.find(v => v.name === voiceName)?.language;
        if (langGender?.endsWith("Female")) {
            return "Female";
        } else if (langGender?.endsWith("Male")) {
            return "Male";
        }
        return null;
    },
    getVoiceLangCode: (voiceName: string, defaultValue: string = null): string | null => {
        const parts = voiceName?.split("-", 2) ?? [];
        if (parts.length === 2 && parts[0] && parts[1]) {
          return `${parts[0]}-${parts[1]}`;
        }
        return defaultValue;
    },
    getVoicePricingBucket: (voiceName: string): PricingBucket => {
        return categories.find(cat => voiceName?.includes(cat.speechModel))?.bucket ?? "Unknown";
    },
    getVoiceSpeechModel: (voiceName: string): SpeechModel => {
        return categories.find(cat => voiceName?.includes(cat.speechModel))?.speechModel ?? "Unknown";
    },
};
